### ISSUE TITLE
Dropdowns and checkboxes are not working.

### ISSUE THREAD

**Issue by theforcepp** [tlovett1/custom-contact-forms#100]
This was loaded with no issues back in December, but now the dropdowns and checkboxes do not work. If it is marked as required, the form of course does not allow you to submit. If it is not required, it comes back with no information submitted. I have tried the sample form that comes with (it has one of each) and that also does not work. 

I have tried deactivating all the plugins except this one... still does not work.

Please help!

**Comment by tlovett1** [comment]
Do you have values set for each field choice?

**Comment by theforcepp** [comment]
I copied your example form and it was running... But it works now.

 

Also after submission, it gives the message with the circles showing processing but they never stop. My customers are annoyed thinking they have to wait for it to stop before they can navigate away.

**Comment by tlovett1** [comment]
Can you link to the form?

**Comment by theforcepp** [comment]
http://theforcepp.com/contact-us/

**Comment by tlovett1** [comment]
Worked fine for me in Chrome. What browser is problematic?

**Comment by theforcepp** [comment]
I’m using chrome, but also see it in safari.

**Comment by tlovett1** [comment]
Windows?

**Comment by theforcepp** [comment]
yes

**Comment by tlovett1** [comment]
Just tested in IE11. Still works for me when I check a few checkboxes. Is this still broken for you?

**Comment by theforcepp** [comment]
Maybe I am not being clear. As you press the submit button, the grey "processing" circles appear and the form submits with a message that says, "Thank you for filling out our contact form. We will be contacting you very soon." But the circles continue to show up as if the form is still processing. I have left this up and waited to find out how long it would continue and it never ceases.

Do you see the circles? Do they ever stop circling? Is intentional design?
![screenshot 2015-04-02 08 26 02](https://cloud.githubusercontent.com/assets/11767218/7066128/504541b8-de74-11e4-8474-1c69892edb5f.png)

**Comment by tlovett1** [comment]
Ah I see now. This is a problem with your theme. Most likely conflicting CSS. Sorry for the confusion.
