### ISSUE TITLE
No simple way to not show the title with ccf_output_form()

### ISSUE THREAD

**Issue by aviemet** [tlovett1/custom-contact-forms#101]
The function checks if the title exists before it makes the HTML, so I tried to remove the title from my post, but couldn't do it on the back end. I ended up going in to the database and removing the title. There should be a tick box in the form edit screen which allows you to include or not include the title.

**Comment by tlovett1** [comment]
Why couldn't you remove the title in the backend? That should be possible.

**Comment by aviemet** [comment]
I was deleting the title in the backend, clicking the save button, and the change did not stick. Tried several times.

**Comment by aviemet** [comment]
If you'd be open to having a tick box to set whether title is displayed, I'd be happy to contribute

**Comment by robneu** [comment]
+1 also having this issue. Once a title has been set, removing it in the admin doesn't seem to work. I'd also +1 the idea of having some method to disable it on the front end while still keeping it in the admin/submissions/etc for organization purposes.

**Comment by tlovett1** [comment]
Agree there should be a tick box or something to not display on the front end. If the title isn't removing itself, then that's a bug.

**Comment by tlovett1** [comment]
6.6.1 fixed the empty titles bug. Thanks guys!

**Comment by robneu** [comment]
:+1:
