### ISSUE TITLE
Passing variable to the form

### ISSUE THREAD

**Issue by suburbiaboy** [tlovett1/custom-contact-forms#102]
Is there any way to pass a value to a hidden field in the form?

For example I want to process some info grabbed from a URL param and pass it as a value in a hidden field. The idea in this case is to record the form's referring page.

Thanks

**Comment by tlovett1** [comment]
Unfortunately, there is not at the moment. You could definitely accomplish it with JS. If you open a PR, I'll be happy to merge it.

**Comment by suburbiaboy** [comment]
No problem, I'll have a think about a good way to achieve it.

Currently this is what I'm doing after adding a specific token in the hidden field (_ref_):

    $ref = $_GET['ref'];
    if ( function_exists( 'ccf_output_form' ) ) {
        ob_start();
        ccf_output_form( 94 );
        $form = ob_get_contents();
        ob_end_clean();
        $form_fixed = str_replace("_ref_", $ref, $form);
        echo $form_fixed;
    }

Perhaps just a get_ccf_output_form($ID) the doesn't echo would be a good start to allow some simple manipulations of the form?

**Comment by tlovett1** [comment]
Perhaps, first of all I make sure you escape `$_GET['ref']` :)
