### ISSUE TITLE
Form submissions don't download

### ISSUE THREAD

**Issue by totalbrand** [tlovett1/custom-contact-forms#103]
I've come across an issue with the plugin and want to check whether others are experiencing a similar problem. When I click on the download submissions icon, my page refreshes but no download occurs. I've tried using Firefox and Safari on Mac.

**Comment by tlovett1** [comment]
It works fine in Firefox for me. Did you check for plugins conflicts?

**Comment by totalbrand** [comment]
I've tried deactivating all plugins and it's still the same. It's strange, clicking the download icon refreshes the page but no windows or prompts for the download. I read somewhere else it could be an export folder permission issue - could this be the case?

**Comment by totalbrand** [comment]
I also tried swapping to a standard theme and same thing seems to be happening. Anything I can test or can I call the download some other way?

**Comment by tlovett1** [comment]
Please email tlovett88[at] gmail.

**Comment by jejuly** [comment]
@totalbrand Issue might be here: https://github.com/tlovett1/custom-contact-forms/blob/master/classes/class-ccf-form-cpt.php#L50

When I removed the trailing space in 'manage_options ', it started downloading correctly.

**Comment by tlovett1** [comment]
Great catch!

**Comment by totalbrand** [comment]
Wow good work @jejuly ! Something so small yet so crucial. I see @tlovett1 has fixed now and works perfectly. Brilliant! I can stop sweating now...
