### ISSUE TITLE
Extracting 'number of submissions'

### ISSUE THREAD

**Issue by totalbrand** [tlovett1/custom-contact-forms#105]
Just wondering if there is any way to extract the 'number of submissions' value for use in my template php code?

**Comment by tlovett1** [comment]
Number of submissions is just the number of child posts of post type `ccf_submission` of a form. You could do something like this:
```php
$submissions = new WP_Query( array(
    'post_type' => 'ccf_submission',
    'post_parent' => FORM_ID,
    'posts_per_page' => 500,
    'fields' => 'ids',
    'no_found_rows' => true,
) );

$num_submissions = count( $submissions->posts );
```

**Comment by totalbrand** [comment]
Genius! Works like a charm, thank you!
