### ISSUE TITLE
Update Issue V 6.6.2

### ISSUE THREAD

**Issue by exp3rt** [tlovett1/custom-contact-forms#107]
I have updated to latest version, but now I can not edit previews form i have created or create new form.

"Custom Contact Forms is experiencing issues.

There is an issue with synchronizing data. Please try deactivating all other plugins and activating the TwentyFifteen theme. If this fixes the problem, you have a plugin or theme conflict. If it does not, please post in the support forums or Github."

I do it, but not work.

**Comment by tlovett1** [comment]
What version did you upgrade from?

**Comment by exp3rt** [comment]
Previews Version, not sure.

**Comment by exp3rt** [comment]
"Note: Version 6.0 breaks backwards compatibility. You will need to perform a database update after upgrading from anything pre 6.0. You may also need to reconfigure some of your forms."
How to perform a database update?

**Comment by tlovett1** [comment]
You should be prompted to perform a database update.

**Comment by exp3rt** [comment]
![ccf prob](https://cloud.githubusercontent.com/assets/9368437/7394600/d38c042c-eea9-11e4-9731-a593b5f37235.jpg)
I have Remove completely and reinstall the plugin. but the problem still is going on.
Also tell me more details about "Perform a Database Update".

**Comment by tlovett1** [comment]
You may have to rebuild your forms. Sorry for the trouble!
