### ISSUE TITLE
Cant choose more than one option with radio buttons

### ISSUE THREAD

**Issue by GreengorillaVideo** [tlovett1/custom-contact-forms#109]
Is there a way to do this. The inability to do this is causing my client to ditch this program in favor of another but I love using it and would like to do so.

Also, it isnt accepting uploads. Are there instructions on making this work?
Chuck

**Comment by GreengorillaVideo** [comment]
File Uploads as attachments is what I meant

**Comment by tlovett1** [comment]
You can use more than one file field. Is that what you mean?

**Comment by GreengorillaVideo** [comment]
When you set up a radio button it only allows one choice from the list.
Sometimes they may choose all the choices that apply and not just one.
Right now if you choose one of the options and then go to pick a second one
the first one "uncheck marks".




*Chuck Wilson*
*(775)-420-2518 - CELL PHONE*


*(888)-477-5376 - Toll Freehttp://greengorillavideo.com
<http://greengorillavideo.com>http://youtu.be/bUh-Fvpo5Cg
<http://youtu.be/bUh-Fvpo5Cg>*

Helping Doctors Get New Patients With Expert Video Marketing!

**Comment by GreengorillaVideo** [comment]
It is set up to choose either/or versus multiple choices.

**Comment by murraysummers** [comment]
That's what checkboxes (and not radio buttons, which are behaving exactly the way they should) are for, no?

**Comment by tlovett1** [comment]
This ^
