### ISSUE TITLE
text colors in paragraph field not formatted properly

### ISSUE THREAD

**Issue by Aksachs** [tlovett1/custom-contact-forms#110]
I have checked the CSS file and code of the form and I can't figure out why this field "Paragraph Text" is not functioning properly (like the other fields of the form). The text color seems to be the same as the background color of the field. (gray on gray, the other fields have it black on gray)

<div data-field-type="paragraph-text" data-field-slug="paragraph-text-5" class=" field paragraph-text-5 paragraph-text field-293  ">
<label for="ccf_field_paragraph-text-5"><br/>
Your Message	</label><br/>
<textarea class=" field-input" name="ccf_field_paragraph-text-5" id="ccf_field_paragraph-text-5" placeholder=""></textarea></p></div>

please help!

this is the webpage where I am having the problem: http://blog.hagarom.com/contact/

thanks

**Comment by Aksachs** [comment]
Although I am now (temporarily?) using a different plugin at this web address I am still interested to know if the problem can be fixed - because otherwise this is a great plugin and I would like to use it!

**Comment by tlovett1** [comment]
I would have to look at your CSS to really solve this problem which most likely is caused by your theme. Sorry!
