### ISSUE TITLE
Upgrade instructions

### ISSUE THREAD

**Issue by murraysummers** [tlovett1/custom-contact-forms#121]
In the instructions, you say 

Note: Version 6.0 breaks backwards compatibility. You will need to perform a database update after upgrading from anything pre 6.0. You may also need to reconfigure some of your forms.

How do I perform a database update? And what reconfiguration might I need? I upgraded from a previous version (sorry, I don't remember but I think it was 5x) and I no longer see any way to specify a recipient for the submission in the settings nor do I see submissions being added to the database.

**Comment by tlovett1** [comment]
You should be prompted to perform a DB upgrade with an admin notice. If you don't see the notice, you're fine.

**Comment by murraysummers** [comment]
Thanks for this answer. I feel better now!
