### ISSUE TITLE
"Success" iframe staying hidden

### ISSUE THREAD

**Issue by murraysummers** [tlovett1/custom-contact-forms#122]
When I submit a form successfully, all I see at the bottom in paragraph format is "Your contact form has been submitted". There is also an iframe in the form that looks like it should be shown on successful submit, but it's (I think) display:none in both the refreshed page form and the successfully submitted form. How can I affect or effect that visibility?

I'm using 6.7.2...

**Comment by murraysummers** [comment]
By the way, I'm using 6.7.2...

**Comment by tlovett1** [comment]
That is intentional. The form works behind the scenes.
