### ISSUE TITLE
Submit on successful recaptcha

### ISSUE THREAD

**Issue by dan-earle** [tlovett1/custom-contact-forms#127]
Hi,
I want the form to submit on successful recaptcha event (recaptcha has "data-callback" js hook).
How would you recommend doing this?
Thanks

**Comment by tlovett1** [comment]
Hmmm, it's definitely possible but I wouldn't recommend it for the sake of your sanity. What's the use case?

**Comment by dan-earle** [comment]
It's mostly about the view on a mobile device, here sometimes after a recaptcha where you have to pick an image you may not have the submit button on screen (that's what our salesman says, he's not very techy)
So the salesman wants it to submit after recaptcha, I can sort of see his point as the recaptcha is the last thing the user completes on my form (its at the bottom) we dont want to loose anyone
my site is orielsystems.com/contact on a mobile device
