### ISSUE TITLE
Form Fields not as tall as text

### ISSUE THREAD

**Issue by waynesl** [tlovett1/custom-contact-forms#131]
I love this plugin.  It has worked flawlessly on several web sites for me.  However, on one web site: http://weslworks.com/contact/ the boxes are half as high as they should be.  is it to do with the theme?  Is there some place in the code where I can tweak the box height?

**Comment by waynesl** [comment]
![contactformcustom](https://cloud.githubusercontent.com/assets/10483162/7665118/5f98e398-fb5e-11e4-99be-f1ed612cb35d.JPG)
![contactformjetpack](https://cloud.githubusercontent.com/assets/10483162/7665119/5f9a4314-fb5e-11e4-9b9a-e6cf6d99d752.JPG)

**Comment by tlovett1** [comment]
Yep, this is from conflicting CSS in a theme or plugin. Good luck!
