### ISSUE TITLE
Form preview: Width Parameter

### ISSUE THREAD

**Issue by theentreprenew** [tlovett1/custom-contact-forms#132]
Hey, i absolutely love this plugin. I literally got to customize every single aspect of it. However im a newbie at all this, don't know much about coding. I have worked on a website and placed the form here: http://www.wildtrekkerslodge.com/reservations but the width of the form fills the entire page, making it look clumsy. I wish to have just half that width or even a third, how can i go about it. Iv attached a screenshot of the page preview
![word](https://cloud.githubusercontent.com/assets/12426115/7697889/22aae750-fe0c-11e4-8f16-e8f4d4def168.jpg)

**Comment by tlovett1** [comment]
Hello, you will need to fix that in your themes stylesheet.
