### ISSUE TITLE
Bootstrap style / markup

### ISSUE THREAD

**Issue by SiamKreative** [tlovett1/custom-contact-forms#134]
Hey Taylor,

What a great plugin I just discovered! Can't believe I never heard about it earlier. You did an excellent job on the UI, it looks like it could be WordPress core :)

But here's the thing, I build most themes on Bootstrap and I'd like to know the best way to style it accordingly. I see two ways of doing it:
* Don't change the markup, style it with Bootstrap mixins (as my theme is built using [bootstrap-sass](https://github.com/twbs/bootstrap-sass)). It's counter productive in the sense that my stylesheet gets bigger.
* Change the markup to match Bootstrap markup. Is there a way to do that? Is there any filters available?

Lemme know what you think @tlovett1

**Comment by tlovett1** [comment]
Changing the markup to Boostrap markup would be very very hard. I would just use Bootstrap mixins.
