### ISSUE TITLE
Theme Graphene and Firefox

### ISSUE THREAD

**Issue by ShanaCC** [tlovett1/custom-contact-forms#135]
Hi there,
I love this form, seriously it helps me a lot. But it doesn't work with theme Graphene in Firefox. I use Chrome, and it works there, I found out about this issue by others complaining.
![issue](https://cloud.githubusercontent.com/assets/12681817/7901586/e7d248d4-078f-11e5-98e4-b19be7f4d93f.jpg)
Could you fix these, because I love that theme, I don't want to change it, and I need this form so bad :) Thank you very much! Keep it up! :)

**Comment by tlovett1** [comment]
Can you link me? This is most likely a problem with your theme's CSS.

**Comment by ShanaCC** [comment]
Hi, oh I fixed it, I found the solution in an other forum, I had to change the css (I don't even know what the hell is that lol), but it fixed the problem. So it's cool now, thank you. I love it! 
I had to copy this: (just fyi. :) 
input[type="text"] {
height: 30px;
width: 300px;
}

Seriously, I'm so happy I could fix it cause this is the best form ever! :) 
Cheers,
Shana
