### ISSUE TITLE
http 302 response and high GPU cycles – Custom Contact Forms

### ISSUE THREAD

**Issue by mbcoding** [tlovett1/custom-contact-forms#141]
Hi, 

Just received notice from one of my clients ISPs, MediaTemple, that their account was having high GPU cycles which will eventually lead to increased charges. In running diagnostics, the CCF plugin rose to the top with almost all queries receiving a 302 response from the server. 

Using CCF 6.7.3 and WP 4.2.2

Thoughts?

Regards,
Mark

**Comment by tlovett1** [comment]
Any more details? What do you mean "queries"? Which URLs are returning HTTP 302?

**Comment by tlovett1** [comment]
@mbcoding ping :)
