### ISSUE TITLE
Not Receiving email Notification from Form

### ISSUE THREAD

**Issue by jasperf** [tlovett1/custom-contact-forms#146]
Forms are submitted, but I do not receive notifications. Regular email test using https://wordpress.org/plugins/check-email/ did work:

```
The test email has been sent by WordPress. Please note this does NOT mean it has been delivered. See wp_mail in the Codex for more information. The headers sent were:
MIME-Version: 1.0\n
From: info@l-me.nl\n
Cc: \n
Content-Type: text/html; charset=iso-8859-1\n
```

result received email:

```
This test email proves that your WordPress installation at http://www.site.nl can send emails. Sent: Thu, 02 Jul 2015 10:34:49 +0000

```
with standard or custom headers (mime) both times the email arrived.
Any ideas how I can debug / fix this?
url: http://goo.gl/DT4f83

**Comment by jasperf** [comment]
Had to change from email address to one added in the  form - form field - instead of relying on a custom one. Then it worked...

**Comment by jasperf** [comment]
When I use field email address as from Gmail will tell the source it is from is not correct. But I still cannot pick info@domainitsat.nl as the email never arrives..

**Comment by tlovett1** [comment]
Hmmm how is your host?

**Comment by jasperf** [comment]
Yeah, it is on shared hosting.  But I will see what they do when I open a ticket later on. Thanks!

**Comment by tlovett1** [comment]
Please email tlovett88 [at] gmail
