### ISSUE TITLE
Form fields not aligned

### ISSUE THREAD

**Issue by rokerm** [tlovett1/custom-contact-forms#148]
I have created a form but the 2 Date of Birth fields are not aligned with the rest of the form so users aren't completing them. One of them is mandatory, so the users keep finding that they are unable to save the form. We have no CSS or anything; it is just a vanilla CCF. What can I do?

http://wp.me/P2Pcpl-zH

We have just realised that the form isn't working at all now - entries are not being accepted.  It doesn't appear to be a hosting issue.

Thanks

**Comment by tlovett1** [comment]
Link doesn't contain a form.
