### ISSUE TITLE
Wordpress 4.1 compatibility?

### ISSUE THREAD

**Issue by james-male** [tlovett1/custom-contact-forms#15]
I have seen Custom Contact Forms version 5.1.0.5 on the Wordpress plugin library and would like to ask if it is compatible with Wordpress version 4.1

Alternatively is the current source code compatible and suitable for production use?

Thanks in advance,

 - James

**Comment by tlovett1** [comment]
@james-male CCF is being redone in the `develop` branch. Please use the plugin there as it is production ready.

**Comment by james-male** [comment]
Thanks, much appreciated!
