### ISSUE TITLE
Recaptcha not working on one site

### ISSUE THREAD

**Issue by dshayne** [tlovett1/custom-contact-forms#154]
I have upgraded this plug-in on three sites and no problems with two of them, but on one site I am getting this error, even though I get a green check mark on the recaptcha:

Your reCAPTCHA response was incorrect.

Any help?
Thanks in advance,
Debbie

**Comment by dshayne** [comment]
And another issue...on most of my sites, the recaptcha requires just putting a check mark in the "I am Not A robot" box and all is well. But on one site, even though I get the green checkmark, it throws up pictures and asks me to find all that have the soup in them, or bread, or...? Any way to stop this? It is annoying and also difficult to see these tiny pictures.
Thanks,
Debbie

**Comment by tlovett1** [comment]
Sorry, that's how the captcha ensures you are a human. Can you link to the website where it is broken?
