### ISSUE TITLE
Failed to Load Resource: Error 403

### ISSUE THREAD

**Issue by jasperf** [tlovett1/custom-contact-forms#155]
On adding an image to a custom post type the client gets the popup  
>Custom Contact Forms is experiencing issues.
>There is an issue with synchronizing data. Please try deactivating all other plugins and activating the TwentyFifteen theme. If this fixes the problem, you have a plugin or theme conflict. If it does not, please post in the support forums or Github.

In the console we see the message:
Failed to load resource: the server responded with a status of 403 (forbidden). This message comes from `site.com/wp-json/ccf/forms/page=?1`

And then the image can no longer be uploaded. Here is a screenshot:
![screen shot 2015-07-31 at 6 35 23 am](https://cloud.githubusercontent.com/assets/344138/9000344/67b18798-374e-11e5-817c-cd05eb4037f3.png)

Did find two related access log lines

`113.89.37.252 - - [29/Jul/2015:13:01:44 -0700] "GET domain.com/wp-json HTTP/1.1" 503 536 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-us; rv:1.9.2.3) Gecko/20100401 YFF35 Firefox/3.6.3" 0 "redirect-handler" "/var/chroot/home/content/68/number/html/index.php" 541614 3498568
89.148.54.150 - - [29/Jul/2015:20:21:04 -0700] "GET domain.com/~user/wp-json/ccf/forms??page=1 HTTP/1.1" 200 3447 "http://domain.com/wp-admin/post.php?post=5991&action=edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36" 11 "redirect-handler" "/var/chroot/home/content/68/number/html/index.php" 1076924 3498568`
 one with the domain in the path leads to a  503 and the one with the home directory in the path leads OK to the wp-json folder although both paths do not exist in the webroot.

This happens using Chrome on Windows 8. I myself do not seem to experience this using Chrome on OSX and I doubt this is OS related. Any ideas why she would be experiencing this uploading images for custom posts? Does CCF create a CCF when there is a synchronisation issue? I doubt that.. The path indicated does not even exist so how that is showing up in the first place I have no idea.

**Comment by TianFroehlich** [comment]
Are you able to modify the forms in the Wordpress-Backend? Or are there no fields anymore?

**Comment by tlovett1** [comment]
Did you try deactivating other plugins/themes to see if there is a conflict?

**Comment by jasperf** [comment]
Yeah after a server upgrade and custom post type fix the error seems to have gone away. probably was the CPT coding error. Closing issue now. Thanks.
