### ISSUE TITLE
Text typed in "Paragraph Text" invisible!

### ISSUE THREAD

**Issue by fabblue** [tlovett1/custom-contact-forms#157]
Hi!

for the sake of testing :) I was filling up a custom form created with this plugin and I noticed that the text written in "Paragraph Text" is actually invisible - that is, the author is aware of what they have typed only by marking the field (see attachment).
I tried both on Mozilla FFox and Chrome - updated versions.
Is this bug already known? Can it please be fixed?
Thank you!
![sshot](https://cloud.githubusercontent.com/assets/13933439/9429887/c9ca32e2-49df-11e5-9892-1f76481fbac2.JPG)

Fabiola

**Comment by tlovett1** [comment]
This is a CSS issue with your theme/other plugins.
