### ISSUE TITLE
All Forms and Submissions Gone

### ISSUE THREAD

**Issue by colorfiremedia** [tlovett1/custom-contact-forms#16]
We installed another plug in on the server as well called formatable.  It is a quick form plug in.  That is all that I can recall that has changed and now all of our Custom Forms are gone and only the short code on the page remains.  Any clue?  Thank you in advance for the help.

**Comment by tlovett1** [comment]
The new plugin does not delete anything. You will need to run the upgrader to make your old data compatible with the new plugin.

**Comment by shinesoftware** [comment]
Hi @tlovett1 maybe he want to tell that your module dosn't show the subscriptions and maybe he thought that the subscriptions have been deleted. I have updated the old data and I have found my old forms but as mentioned in the issue #22 I have found many little bugs. Any Clue?

**Comment by tlovett1** [comment]
What version of the plugin are you running?

**Comment by shinesoftware** [comment]
@tlovett1 nevermind! now we use another module. Maybe in the next project we will use your module. thanks
