### ISSUE TITLE
"email@example.com" is not translated

### ISSUE THREAD

**Issue by pyrog** [tlovett1/custom-contact-forms#160]
This string is not translated in [/classes/class-ccf-field-renderer.php#L793](https://github.com/tlovett1/custom-contact-forms/blob/4390e8195ed0de6b7665a861d20d353f24f54920/classes/class-ccf-field-renderer.php#L793)

**Comment by tlovett1** [comment]
Will be fixed in next minor release.

**Comment by pyrog** [comment]
Thank you :smile:
