### ISSUE TITLE
Notifications not received. Help!

### ISSUE THREAD

**Issue by dsmallwood1982** [tlovett1/custom-contact-forms#163]
My client is not receiving the notifications to their email account. We did a test. Their gmail.com email received the notification but when I switched to peverett@truexcellencestaffing.com their company email it doesn't receive it. Let me know if there is a solution. 

Thank you in advance for the support!

**Comment by tlovett1** [comment]
Do WordPress lost password emails work?

**Comment by dsmallwood1982** [comment]
I'm not sure, How can I find out? Does it affect it some how?
