### ISSUE TITLE
cannot insert form

### ISSUE THREAD

**Issue by tymelocker** [tlovett1/custom-contact-forms#164]
I click on add form and the screen jumps to the top of the page and nothing happens. I have two forms saved and no other form plugins activated. Using Highend Theme. Thank you

**Comment by tymelocker** [comment]
I was not able to add it when I was using visual composer. I had to be in classic mode to insert it. I was able to change it back to front end mode and it stayed and I was able to move it in the drag and drop editor from there.

**Comment by tlovett1** [comment]
Try deactivating visual composer and other plugins to see if there is a conflict.
