### ISSUE TITLE
Title removal from form + how to remove ":" next to each label in notification emails. Please Help ! :)

### ISSUE THREAD

**Issue by Daftworld** [tlovett1/custom-contact-forms#167]
Hi there,

Is it possible to remove the Title from the form ?
I mean this one : 
"Title - The main title for the form. This will be shown to the end user above the form".

Could someone help which file I have to modify in order to remove this ?
And what exactly I have to remove. 

Thanks a lot,

Daft

PS Also, is it possible to modify what is displayed in the notification/mail.
In my notification email, for each label name, I'm having " : " right after the label. Is it possible to remove the " : " somewhere ?

**Comment by Daftworld** [comment]
Does someone have a clue ?? It's quite urgent ! :)

Thanks

**Comment by tlovett1** [comment]
You can just leave the title blank. There is also a filter to not display the title.
