### ISSUE TITLE
Error displaying en editing forms in the plugin

### ISSUE THREAD

**Issue by RubenJnl** [tlovett1/custom-contact-forms#177]
Since last update to 6.8.2 and before and after the WordPress 4.3.1 update I've been experiencing issues with the contact forms.

I can't view forms and submitted data in the plugin or edit the forms. 
The forms are still working for the visitors but adding new and editing forms is causing issues.
When saving a form the message *experiencing issue* pops up:

I've disabled all other plugins and used the – default – twentyfifteen theme but that doesn't help. Even removing and re-installing the plugin with all other plugins disabled and default theme doesn't help. Forms are saved but can't edit or view them anymore.
Except from an font issue I can't find any errors in my console, but i don't think the font issue has anything to do with not showing the form or submissions.
```downloadable font: OS/2: bad linegap: -64 (font-family: "form-manager" style:normal weight:normal stretch:normal src index:1) source: http://fiatpandaclub.nl/wp-content/plugins/custom-contact-forms/fonts/form-manager.woff```

**Comment by tlovett1** [comment]
Not able to reproduce this one. What browser are you using? Is this problem still occurring?

**Comment by RubenJnl** [comment]
There's no difference in browsers, at the moment I use Firefox Developer Edition 43, or Firefox 41 or Chrome 45. I've tried it in all three.
Should there be some specific permissions on files?
The problem is still occuring: No list of submissions in already created forms only a count in the list with all forms.
Also preview isn't working anywhere.
![screenshot-2015-09-30 08-57-41](https://cloud.githubusercontent.com/assets/429526/10186469/8d0f3cbe-6751-11e5-952c-cc67cf9a0448.png)
![screenshot-2015-09-30 08-58-33](https://cloud.githubusercontent.com/assets/429526/10186470/8d0f6b26-6751-11e5-95ae-933abb863012.png)

On saving the form this happens
![screenshot-2015-09-30 09-00-18](https://cloud.githubusercontent.com/assets/429526/10186519/f38375d2-6751-11e5-93fc-279b374b3258.png)

On saving it again it's been added to the form list twice
![screenshot-2015-09-30 09-00-52](https://cloud.githubusercontent.com/assets/429526/10186530/ff774cb0-6751-11e5-91fc-b4332c556ed6.png)
