### ISSUE TITLE
File Upload Missing with V. 6?

### ISSUE THREAD

**Issue by elkampong** [tlovett1/custom-contact-forms#18]
Hi there,

I understand that backwards compatibility was broken with V.6, but when rebuilding my forms across all of my websites I can no longer find a "file upload" option. This is an important feature for some of the websites where I am using this plugin - am I missing something or has it been disabled?

Thanks

**Comment by tlovett1** [comment]
It has been removed from the plugin for now. You will need to revert to an old version to use it. Sorry!
