### ISSUE TITLE
Error displaying en editing forms in the plugin

### ISSUE THREAD

**Issue by RubenJnl** [tlovett1/custom-contact-forms#186]
Recently I created issue https://github.com/tlovett1/custom-contact-forms/issues/177. It was closed and I couldn't open it again. I'm still having issues with saving forms and displaying submitted data.
In my last [comment](https://github.com/tlovett1/custom-contact-forms/issues/177#issuecomment-144309406) – after it was closed – I added some more information.
Is it possible to try and reproduce it again? I've tried everything from removing all other plugins and returning to the default template without results.
Could it be that there are some rights are set wrong on plugin files or folders?

**Comment by tlovett1** [comment]
Can you email me? tlovett88 [at] gmail
