### ISSUE TITLE
Syntax conflict with ASP tags?

### ISSUE THREAD

**Issue by deltafactory** [tlovett1/custom-contact-forms#19]
I noticed a new templating markup in files like this:
https://github.com/tlovett1/custom-contact-forms/blob/master/classes/class-ccf-form-manager.php#L54

Won't the <% %> tag notation conflict with hosting environments that have ASP-tags enabled? This is likely a minority, but enough to cause problems.

**Comment by tlovett1** [comment]
Is this a problem you are having? CCF is using underscores style templating which is very common.

**Comment by deltafactory** [comment]
No, not personally. I see its use is creeping in to WordPress core as well. If core breaks compatibility then no reason to be concerned. Thanks.
