### ISSUE TITLE
Is there a reason why forms and submissions are public post types?

### ISSUE THREAD

**Issue by robneu** [tlovett1/custom-contact-forms#190]
Currently both forms and form submissions are using public post types. I was wondering if there's a specific reason for this or if they were just made that way by default.

I'm asking this because it presents a bit of an SEO issue and also makes it really easy for anyone to find most sites using the plugin [via Google](https://www.google.com/search?q=inurl:ccf_submission).

Would it be possible to make these private? This would fix any SEO issues and also probably prevent some odd behavior with various plugins. WordPress SEO, for example, adds the forms to the sitemap and attempts to add SEO metadata to the front-end entries.

**Comment by robneu** [comment]
Looks like this may have been fixed in 956ae544fb20dab2c3e86b9299eb53b4dc62802f. If so, feel free to close this out.

**Comment by tlovett1** [comment]
Awesome!
