### ISSUE TITLE
I keep getting a message for this ... is there a fix?

### ISSUE THREAD

**Issue by sjulau** [tlovett1/custom-contact-forms#191]
"Custom Contact Forms is experiencing issues.
There is an issue with synchronizing data. Please try deactivating all other plugins and activating the TwentyFifteen theme. If this fixes the problem, you have a plugin or theme conflict. If it does not, please post in the support forums or Github."

**Comment by kryzaal** [comment]
The same

**Comment by tuamo** [comment]
Check the console for errors. In my case, the WP REST API that CCF comes with didn't load for some reason. Fixed it by installing it manually from here: https://wordpress.org/plugins/json-rest-api/

**Comment by kryzaal** [comment]
Installation of wp-rest-api didn't solve the problem for me.
No error in console.

**Comment by tlovett1** [comment]
Did you try deactivating other plugins?

**Comment by sjulau** [comment]
I just deactivated all plugins and reactivated one by one and it works and they work! cool!!
