### ISSUE TITLE
Form broken after update - don't know where to do database update?

### ISSUE THREAD

**Issue by jomarie** [tlovett1/custom-contact-forms#195]
Hi there,

The contact form on our site updated somewhere during an automatic process. When I log into our Wordpress Dashboard, I don't get any notice to do the required database update after the 6.9.0 form upgrade. Is there any other way I can do the database update so the form can work again?

Currently, instead of showing the form, all it does is [customcontact form=1]

**Comment by tlovett1** [comment]
You should have seen a notification in your dashboard.
