### ISSUE TITLE
Export/Import is broken

### ISSUE THREAD

**Issue by sajadghawami** [tlovett1/custom-contact-forms#197]
Hey there,

it seems like the export is broken.

Whenever a form is exported, and imported, the individual fields gets switcht. The first becomes the last and so on.

Anyone had the same issue?

**Comment by tlovett1** [comment]
Will look into this one.

**Comment by tlovett1** [comment]
Not able to reproduce. Anymore details?

**Comment by vanilium** [comment]
I have some bug... after import, fields in the form are shuffled
