### ISSUE TITLE
email notification not working

### ISSUE THREAD

**Issue by CapSoc** [tlovett1/custom-contact-forms#198]
Not receiving emails for form submittals.  Site is set up the same as other sites, same host, others work, this doesn't.

**Comment by moonshinemadness** [comment]
I love this plugin but I'm also having this issue. I have the notification activated and am not receiving any notifications.

**Comment by tlovett1** [comment]
Is WordPress lost password functionality working?

**Comment by moonshinemadness** [comment]
Hi Taylor,

The lost password function is working.
I'm still having this issue - the forms seem to be storing correctly, but I
just can't get those email notifications. I've checked in every email
folder- no dice. I'm now also getting the error form when trying to save.

Any help will be greatly appreciated.

Cheers,
Mel.

On Tue, Dec 15, 2015 at 6:00 AM, Taylor Lovett <notifications@github.com>
wrote:

> Closed #198 <https://github.com/tlovett1/custom-contact-forms/issues/198>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tlovett1/custom-contact-forms/issues/198#event-491411641>
> .
>



-- 
<http://www.moonshinemadness.com/>

Director/Designer of Moonshine Madness
Paddington, Brisbane
