### ISSUE TITLE
Save button has no effect

### ISSUE THREAD

**Issue by bkbeachlabs** [tlovett1/custom-contact-forms#20]
Hi there, the plugin is great and easy to use. However, when I press "Save" the activity indicator spins and disappears as if its saving. Then I close the create form window and no form has been created. The same thing happens if I try to create a form from a post.

Please let me know soon! I'm working on a site for a client and I'd prefer to use your form but I'll have to move on to a new option if I don't find a solution for this.

**Comment by tlovett1** [comment]
Can you look at the result of the AJAX request? In Chrome you can look at the network tab within the developer tools to accomplish this.

**Comment by bkbeachlabs** [comment]
Hi Taylor,

I’m not familiar with AJAX, but I think this is the response:
{"wp-refresh-post-lock":{"new_lock":"1421295423:1"},"wp-auth-check":true,"server_time":1421295423}

Thanks for the quick reply,
Andrew

**Comment by tlovett1** [comment]
Hey Andrew, that is a different AJAX request. That is one sent by WordPress core. You will need to find the one sent to /wp-json/ccf/forms/

**Comment by bkbeachlabs** [comment]
Oh interesting, I see that request but Chrome is saying the response has no data. Is there some setting I need to change to enable this?

**Comment by tlovett1** [comment]
Can you try enabling a default theme and disabling other plugins to see if there is a conflict?

**Comment by GJBRYAN** [comment]
I am having a similar problem.  I can create new forms and save them, but if I try to edit anything, the changes do not actually save.  

I just checked where you suggested and the message is highlighted in red and says: 501 Method Not Implemented after I try to save it.

Any suggestions?

**Comment by tlovett1** [comment]
501 method not implemented means your host does not support RESTful requests using HTTP verbs like PUT or DELETE. You will need to contact your host.
