### ISSUE TITLE
CPTs show up in XML Sitemaps

### ISSUE THREAD

**Issue by cmmarslender** [tlovett1/custom-contact-forms#201]
https://github.com/tlovett1/custom-contact-forms/blob/master/classes/class-ccf-submission-cpt.php#L42
and
https://github.com/tlovett1/custom-contact-forms/blob/master/classes/class-ccf-form-cpt.php#L590

are both marked as public, so they show up in the sitemap.xml for yoast sitemaps (possibly other sitemap plugins) but the actual URLs end up 404ing

**Comment by tlovett1** [comment]
Pushed in 7.1
