### ISSUE TITLE
cannot activate notification

### ISSUE THREAD

**Issue by yelch** [tlovett1/custom-contact-forms#208]
Hi! Thank you for this great plugin.
I have an issue activating the notifications: every time I change to yes after closing the dropout or saving directly and reopening the form in edit mode, the notification is deactivated...
Help appreciated.
Thank you, Daniel

**Comment by tlovett1** [comment]
This should have been fixed in version 7.2.3

**Comment by yelch** [comment]
The update just appeared. 
Fix is confirmed! Thank you!

**Comment by tlovett1** [comment]
Please leave a 5 star review here - https://wordpress.org/support/view/plugin-reviews/custom-contact-forms

**Comment by yelch** [comment]
Done :-)
