### ISSUE TITLE
WordPress Database Error on New Install

### ISSUE THREAD

**Issue by robneu** [tlovett1/custom-contact-forms#21]
First of all... AWESOME plugin. Wow.

The one thing that I'm seeing on a fresh installation is a database error after installing the plugin.

`Table 'database-name.wp_customcontactforms_forms' doesn't exist` related to ` SELECT * FROM wp_customcontactforms_forms`

Looks like this has something to do with the old custom database tables from the original plugin, but I'm not sure? Anyway, keep up the great work on this and let me know if there's anything I can do to help debug.

Edit: Checked this against both the wp.org and the github version and the issue is present in both.

**Comment by robneu** [comment]
It looks like the problem is in `classes/class-ccf-upgrader.php` within the `update_nag` method. I'm guessing it needs an extra check in there to make sure the old database table actually exists before firing the nag.

**Comment by tlovett1** [comment]
b3a96fd42812 should fix this.

**Comment by robneu** [comment]
:+1:
