### ISSUE TITLE
Videomail integration?

### ISSUE THREAD

**Issue by binarykitchen** [tlovett1/custom-contact-forms#217]
Hello there

I have a cool idea here! How about adding videomail support?
https://github.com/binarykitchen/videomail-client

Check out the live site https://videomail.io which explains it pretty much.

That would enhance Wordpress forms enormously. With the videomail client this recording feature can be included anywhere with one Javascript file only. No need for Flash. Works on all modern browsers (except Safari) and even on Androids.

Another good reason is to support Sign Language (Deaf people). They prefer to sign instead of writing, i.E. in a contact form. Here an example: https://binarykitchen.com/contact/action/add/

If you are open to this idea, I am more than happy to assist or even to submit a PR.

Let me know ...

**Comment by binarykitchen** [comment]
@tlovett1 ping?

**Comment by tlovett1** [comment]
Sorry didn't read the whole thing. Seems really cool. How would you feel about creating an extension plugin for it?

**Comment by binarykitchen** [comment]
Why not @tlovett1 - are there any examples out there for a custom-contact-forms extension? And can I count on some guidance from you?

**Comment by binarykitchen** [comment]
hellllooo??

**Comment by tlovett1** [comment]
No examples of extension plugins. Yes you can count on guidance.

**Comment by binarykitchen** [comment]
@tlovett1 then i need at least a starting point how to write an extension plugin for your custom-contact-forms plugin please

**Comment by tlovett1** [comment]
You will have to dive into the code unfortunately. Sorry!

**Comment by binarykitchen** [comment]
but then, how come you wrote code for extension plugins but haven't tested, nor used it nor added an example? to me, this does not look so good but you probably have a good reason for that?
