### ISSUE TITLE
Radio buttons and checkboxes don't work on mobile devices

### ISSUE THREAD

**Issue by wbower** [tlovett1/custom-contact-forms#219]
I've tried radio buttons and checkboxes on smartphone and tablet using various browsers (Dolphin, Chrome) and they do not function properly. The text for the items are displayed but the radio and checkbox next to the items do not display.

Drop-down lists do work, however on mobile devices it is not evident the input field is a drop-down since no down arrow appears inside the input box.

**Comment by tlovett1** [comment]
Can you provide a link?

**Comment by wbower** [comment]
Here is the link http://kvc.ibower.ca/membership/

**Comment by wbower** [comment]
Any update on this issue? The same thing is happening on laptop with Chrome browser.

**Comment by tlovett1** [comment]
Sorry, there is CSS in your theme causing form elements to not display properly.

**Comment by wbower** [comment]
Thanks for the hint. I found the solution. I installed the Simple Custom CSS plug-in and added the following lines in the custom CSS:
/* -- Radio Button Fix -- */
input[type="checkbox"] { -webkit-appearance: checkbox; }
input[type="radio"] { -webkit-appearance: radio; }
input[type="submit"], input[type="button"] { -webkit-appearance: button; }
select { -webkit-appearance:textfield; }

The radio buttons and checkboxes now appear both in Chrome on my PC and mobile device.

Wayne
