### ISSUE TITLE
New CF version: bugs

### ISSUE THREAD

**Issue by shinesoftware** [tlovett1/custom-contact-forms#22]
First of all thanks for your module.
I have discovered various issues in the last version of the module:

## Form list records are not visible

Why the form list is empty ?
![schermata 2015-01-15 alle 11 41 32](https://cloud.githubusercontent.com/assets/1553035/5756038/809048fa-9cab-11e4-80a2-138cf44021cf.png)

## Old Submissions are not shown
I have clicked on the Form > Form & Submission but I don't see the old submissions. How have I to read them?
![schermata 2015-01-15 alle 11 56 57](https://cloud.githubusercontent.com/assets/1553035/5756260/b0aa35da-9cad-11e4-9b90-412ca7c35e93.png)

![schermata 2015-01-15 alle 11 53 26](https://cloud.githubusercontent.com/assets/1553035/5756172/2c5c3fc6-9cad-11e4-8dd5-b20d0fa8f076.png)

## Dashboard doesn't show the last submissions
In the previous version I was able to read the last submission on the dashboard, why it is not available anymore?

## Captcha 
the Captcha element is not available anymore in the Special Fields
![schermata 2015-01-15 alle 12 53 02](https://cloud.githubusercontent.com/assets/1553035/5756922/7ec95c0a-9cb5-11e4-92d5-3ef39e8f08c0.png)

## Email Template
The old template email was better than this new template. This is awful to say but this is what the site owner told us. Is there a way to fix or customize it? Can we use the subject posted by the visitor as subject of the email?

New Template:
![schermata 2015-01-15 alle 17 32 03](https://cloud.githubusercontent.com/assets/1553035/5761674/44079adc-9cdd-11e4-97af-b238e431f47c.png)

Old Template:
![schermata 2015-01-15 alle 17 32 15](https://cloud.githubusercontent.com/assets/1553035/5761676/444055b6-9cdd-11e4-94ec-4d4302034344.png)

Thanks

**Comment by tlovett1** [comment]
Hey,

Captcha and dashboard module are not available in the new plugin (yet).

Regarding forms and submissions list, I will need to see the result of the AJAX request to tell you what is happening.

**Comment by shinesoftware** [comment]
First of all thanks Taylor for your precious help. I have updated the list of the issues.

**Comment by rjmclan** [comment]
i have just installed your plugin on my WP site, which is exactly what i am looking for. I can create forms and save them, but when i click the add to page link i get nothing. I have looked around for the shortcode usage but can't find it. 
Help?

**Comment by Bugzippy** [comment]
Form submissions are not working to multiple receivers only message from wordpress

**Comment by Bugzippy** [comment]
Thanks so much Taylor for this lovely plugin the question I must ask is after updating can we uninstall or delete and reinstall ver 5.x until the submissions to various email addresses issue is sorted? Thanks

**Comment by tlovett1** [comment]
You can uninstall and reinstall version 5.x at anytime even after upgrading the DB.
