### ISSUE TITLE
Responsive reCAPTCHA?

### ISSUE THREAD

**Issue by jezthomp** [tlovett1/custom-contact-forms#232]
Is there anyway to make the reCAPTCHA responsive, or change the google side of things to compact?

**Comment by tlovett1** [comment]
The reCAPTCHA is small enough that it should fit on the smallest of screens. Not sure how you would make this responsive.

**Comment by jezthomp** [comment]
The width is 304px which on a iPhone portrait is al little tight when the overall width is 320px?

**Comment by tlovett1** [comment]
We now have another CAPTCHA option in 7.7
