### ISSUE TITLE
Email notifications not arriving (FIXED)

### ISSUE THREAD

**Issue by flyingmonkeyair** [tlovett1/custom-contact-forms#237]
UPDATED 
I have the latest version of the plugin and it stopped sending email notifications a couple updates ago. Installing the Easy WP SMTP fixed the problem.

**Comment by pepamint** [comment]
How do you use this? Thanks

**Comment by flyingmonkeyair** [comment]
Just install the Easy WP SMTP plugin, find the settings, and configure it. It's really simple, then it seems to work in the background with CCF. I started receiving emails immediately.
