### ISSUE TITLE
post to different endpoint

### ISSUE THREAD

**Issue by aliceriot** [tlovett1/custom-contact-forms#238]
Hey there!

I wasn't able to figure this out from the documentation. Is there an easy way to set up a form which posts (ideally JSON) to an endpoint other than the wordpress site itself?

I'm not at all a wordpress developer, so forgive my ignorance, but our blog at work is a wordpress site, and I'm looking to put a signup form on the blog that posts to a public endpoint on our main Rails app.

Is this possible out of the box with this plugin? If not, would it be easy for me to add? Thanks!

**Comment by zakius** [comment]
it doesn't really make sense to use this plugin for it (the main power of this one is displaying data received from forms in your dashboard), you could simply use any HTML based form powered by AJAX, just remember to enable CORS on your another service

and if you want to use the form builder, you probably can just build it and copy code

**Comment by aliceriot** [comment]
I let this get a little stale! We ended up writing our own plugin.
