### ISSUE TITLE
Add Form Doesn't Work with Visual Composer

### ISSUE THREAD

**Issue by santadavid** [tlovett1/custom-contact-forms#24]
The Add Media button appears with the Visual Composer for WordPress editor but does not add the form.

**Comment by tlovett1** [comment]
Are there any JS errors?

**Comment by santadavid** [comment]
I didn't look for any JS error so I'm not sure. When I tried to add the form with the editor there was no action. It appeared that it did nothing. I've restored the plug-in to the old version and no longer have a setup with the new plug-in that I can test anything. Sorry.
