### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'p[t.field].querySelectorAll')

### ISSUE THREAD

**Issue by jezthomp** [tlovett1/custom-contact-forms#242]
I’m getting the following JS error, not sure if its something i’ve done but a normal form setup with current version.

`TypeError: undefined is not an object (evaluating 'p[t.field].querySelectorAll')
(anonymous function)form.min.js:1:10457
forEach
forEachunderscore.min.js:4:612
(anonymous function)form.min.js:1:10091
forEachunderscore.min.js:4:688
(anonymous function)form.min.js:1:9312
forEachunderscore.min.js:4:688
(anonymous function)form.min.js:1:7012
jjquery.js:1:27314
fireWithjquery.js:1:28123
readyjquery.js:1:29967
Jjquery.js:1:30327`

**Comment by tlovett1** [comment]
Can you link to where this is happening?

**Comment by bthibault** [comment]
I'm also getting this.. was there a fix in place?
