### ISSUE TITLE
mobile resizing not available

### ISSUE THREAD

**Issue by hleong** [tlovett1/custom-contact-forms#243]
The contact form does not resize automatically for mobile or tablet devices. Is there a fix for this? Thanks in advance!

**Comment by tlovett1** [comment]
The form should resize. Perhaps an issue with your theme?

**Comment by hleong** [comment]
Would you mind looking at my code in my website? The form appears to be in a static position, I.e. it isn't responsive with other widgets in the page. But I don't have this issue with other plugins so I don't think it's a problem with my theme. Website is jaimechic.com/contact-us

**Comment by tlovett1** [comment]
Can you email tlovett88 [at] gmail?
