### ISSUE TITLE
[Proposal] Basic templating in redirect URL

### ISSUE THREAD

**Issue by connorjburton** [tlovett1/custom-contact-forms#247]
Happy to be corrected on the current implementation, I may be completely wrong.

**Scenario**

Lets say I am developing a recruitment website, they list a bunch of jobs on there which you can apply to. My structure is something like `job archive` => `job single` => `apply/j?=JOBID`. Once you have filled out the CCF on `apply/j?=JOBID` it should redirect to `/applied?j=JOBID` page that shows the details of the job you have applied to and similar jobs so you can continue your job hunt.

**Current State**

CCF doesn't allow any form of templating for the URL or passing of data, so there isn't a way in CCF to implement the above.

**Proposed Solution**

Allow a URL to consist of `##object.prop##` parts, each part will be parsed with regex and `split('.')`, this will give us the `object` and it's `property`, some examples of this would:

`/applied/?j=##post.id##` = gets the current posts ID
`/applied/?=##get.j##` = gets `$_GET['j']`

(If we want to add `$_POST` we are going to have a conflict)

For `get` and `post` the easiest way forward it to use https://github.com/sindresorhus/query-string - however this is an extra dependency and we don't currently use anything like `browserify` so it would be an extra HTTP request.

**Issues**

I had a quick play with this idea and the first problem I encountered was with the regex, I put together this `/(?<=##)(\w*\.\w*)(?=##)/g`, however JS does not currently support lookaheads, so this may be little more involved to parse.

The other main issue I can see is with getting data to `post`, I am not sure we would want to expose all this data in JS (maybe we already do?), possibly we could limit the fields that do get exposed.

This is just a proposal for an issue I personally encountered, however it may not be wildly encountered and not necessary to be in the core. Let me know your thoughts

**Comment by tlovett1** [comment]
How about just adding a filter for the redirect URL?

**Comment by connorjburton** [comment]
Hey, that's a great and much less complex solution ha. Thanks
