### ISSUE TITLE
Limit to number of fields?

### ISSUE THREAD

**Issue by erraid** [tlovett1/custom-contact-forms#25]
Hello, I created a contact form with several fields. Now I want to add more, but after I 'save form', they don't show up. Is there a limit to the number of fields in a form? If not, why can't I save additional fields? Thanks for any help!

**Comment by tlovett1** [comment]
Sounds like a JS error. Can you send me the result of the AJAX request?

**Comment by erraid** [comment]
Dear Taylor,
thank you for your quick reply! I don't know what a JS error or an AJAX request are.
I'm in WordPress, clicked on Forms, clicked on the form I created, clicked Manage Form, entered new fields, saved it. But they don't appear when I click on Manage Form again.
I also inserted the form into a Page, where it shows up exactly as it does under Forms -- also without the new fields.
Beth

**Comment by tlovett1** [comment]
Can you email tlovett88 [at] gmail?

**Comment by erraid** [comment]
Yes. I just forwarded my email to the gmail account.

**Comment by tlovett1** [comment]
Result of non-unique slugs.
