### ISSUE TITLE
Hide Form Title?

### ISSUE THREAD

**Issue by tsquez** [tlovett1/custom-contact-forms#250]
Love the plugin, great work. I have switched from Gravity Forms to your plugin and I love it!!! Again great work.

I was wondering if it was possible to hide the title of the form in some way?

**Comment by tlovett1** [comment]
I'd love to know what got you to switch!

A hide title feature will be in the next version in the next day or so.

**Comment by tsquez** [comment]
That would be awesome. 

Basically your plugin provides everything that GF does. There are still a few things I think yours could use but overall its fast and easy.

**Comment by tlovett1** [comment]
Added in 7.8. Any other important features you need?
