### ISSUE TITLE
Form not working with required fields

### ISSUE THREAD

**Issue by izzetta** [tlovett1/custom-contact-forms#251]
Hello, I'm new here. I'm setting a contact form as a booking request form. I have some fields which are required (like Name, Email, Booking period, ecc), **but the form is not working when I set these fields as required**. It works only when I disable "required" option. Where di I go wrong? Any ideas? Thanks. 

http://www.la-cesa.it/prenota/

**Comment by tlovett1** [comment]
The form worked when I filled all the required fields in.

**Comment by izzetta** [comment]
Hi, that's because I left all the fields "not required". Try it now. Thanks. 

http://www.la-cesa.it/prenota/

**Comment by tlovett1** [comment]
You must set "Option Value" for each checkbox/radio/dropdown
