### ISSUE TITLE
An unknown error occured

### ISSUE THREAD

**Issue by Husbandman** [tlovett1/custom-contact-forms#252]
I am trying to use your plugin, but my two forms I have created both give "An unknown error occured" I have not idea what to do. The website is http://montanashedcenter.com

**Comment by tlovett1** [comment]
Can you link me to the contact form?

**Comment by Husbandman** [comment]
I created a new form and it works. I tried that earlier, but it didn't. I think it had something to do with changing the domain of the site after I installed it.

**Comment by Husbandman** [comment]
I was wrong it is not working. The form does not give an error when login, only when logged out. "Require User to Be Logged In:" is set to no.

**Comment by tlovett1** [comment]
Need to see the contact form.

**Comment by Husbandman** [comment]
Your update solved our problem.
