### ISSUE TITLE
Not allowing me to add to page 

### ISSUE THREAD

**Issue by ciaprior** [tlovett1/custom-contact-forms#254]
Hello, I am trying to use your form on my companies website. I have installed the plug in and created a form, but there is only a save button, no add to page, and in the page, itself, I have a button that says add to page, but when I click on it, nothing happens. I am using divi by elegant themes.

**Comment by linkll59** [comment]
Hello Taylor Lovett,  I am trying to use your form on my website. I have installed the plug in and created a form, but there is only a save button, no add to page, and in the page, itself, I have a button that says add to page, but when I click on it, nothing happens. I does not include the origin of the problem you could advise me? Thank you for this plugging.

**Comment by tlovett1** [comment]
Please email tlovett88[at] gmail
