### ISSUE TITLE
Form Not Submitting

### ISSUE THREAD

**Issue by brettallica** [tlovett1/custom-contact-forms#259]
I'm sure it's a setting that I'm missing again, but for a new client's site that I'm configuring I cannot get the form to submit to the e-mail address that I have configured. I have this plugin installed on another client's site and it works perfectly, and I didn't configure anything special about that form -- I simply put in the e-mail address where I wanted the form data to land and it has worked perfectly. For some reason it's just not working on this new site, though. 

I am currently working out of a staging directory and it has a tilde in the URL, so I'm wondering if that has anything to do with it.

**Comment by tlovett1** [comment]
Screenshot of your notification settings?

**Comment by brettallica** [comment]
Thanks for the quick reply. Here is the notification settings section. I had to break it into two screenshots to capture the entire thing:

![notification settins screenshot 01](https://cloud.githubusercontent.com/assets/16442162/14212080/132f3c48-f7e6-11e5-9075-c4207d3da2f3.png)
![notification settins screenshot 02](https://cloud.githubusercontent.com/assets/16442162/14212083/139c8b2c-f7e6-11e5-9dc6-1336a245bcf1.png)

**Comment by brettallica** [comment]
Any thoughts? Thank you in advance for your continued support. 

I was thinking about maybe just trying to install a new form to see if this one is has some kind of cached setting that simply won't go away or something. I also launched the site so that it's on an actual domain now and not a temporary staging directory.

**Comment by tlovett1** [comment]
Looks like you are pulling the "Reply To Email" from the "Name" field.
