### ISSUE TITLE
Add wp filter to hide / deactivate TinyMCE integration?

### ISSUE THREAD

**Issue by WPWiseOwl** [tlovett1/custom-contact-forms#26]
The TinyMCE area can easily become cluttered and I want to provide an alternative way to insert the form. I want to provide a more consistent UI experience for those that use my custom plugin. I'd also rather not have to field any questions specific to the TinyMCE functionality you've added. Thanks for your time and consideration!

"TinyMCE Integration" refers to:
* TinyMCE Button
* Any Associated Dialogs
* Any Content Editor Extensions Introduced

**Comment by tlovett1** [comment]
What would you prefer?

**Comment by WPWiseOwl** [comment]
I'd like to just hook a filter and then return false to turn off / disable all the TinyMCE enhancements that your plugin makes while activated. That's all.

**Comment by tlovett1** [comment]
The plugin only adds the TinyMCE preview and nothing else. Is that what you are referring to?

**Comment by WPWiseOwl** [comment]
Yes. Sorry for not being clearer.

**Comment by tlovett1** [comment]
I'll push something into the next version for this.

**Comment by WPWiseOwl** [comment]
Great! Thanks. :-)

**Comment by tlovett1** [comment]
^ Does this work for you?

**Comment by WPWiseOwl** [comment]
Can it be changed to also disable the CCF shortcode generator button above
the editor?

If not, what you've done already is quite enough. It's a great improvement
IMO either way. Thanks so much for your time.

**Comment by tlovett1** [comment]
You can just do something like this:

```php
remove_action( 'media_buttons', array( CCF_OBJECT, 'action_media_buttons' ) );
```

**Comment by WPWiseOwl** [comment]
Works for me! Thanks again.
