### ISSUE TITLE
contact form checkboxes and radio buttons not showing on site.

### ISSUE THREAD

**Issue by TheYodelman** [tlovett1/custom-contact-forms#261]
The form I made looks perfect in the preview and mostly okay on the site except the checkboxes and radio buttons are missing on the site page. I'm using the Upfront theme from wpmu dev. Any thoughts on how to fix that?
Here's the page:
http://yodelinghalloffame.com/join-2/

**Comment by TheYodelman** [comment]
After testing in several browsers, the problem seems to be related just to Firefox. Opera, Safari, Chrome all showed the missing elements and everything works.

**Comment by tlovett1** [comment]
Hey, this is just a CSS issue in your theme. It should be easily resolvable.

**Comment by TheYodelman** [comment]
Taylor. Any chance you could point out what that issue is? Then,I can take it from there
Thanks for your help.

**Comment by TheYodelman** [comment]
Taylor - I got it figured out with some help from the Mozilla support and the theme developers. Thanks for a really great contact form!

**Comment by tlovett1** [comment]
Please leave a 5 star review :)
