### ISSUE TITLE
Support for Customize Posts Plugin

### ISSUE THREAD

**Issue by bsusala** [tlovett1/custom-contact-forms#263]
Please see https://github.com/xwp/wp-customize-posts/issues/128#issuecomment-216654726.
Any chance to add support for Customizer section in their innovative plugin?

**Comment by westonruter** [comment]
See https://github.com/tlovett1/custom-contact-forms/pull/264 😄

**Comment by bsusala** [comment]
Cool :)

**Comment by BurlesonBrad** [comment]
{cough} @tlovett1 _merge?_ 
:wink:

**Comment by tlovett1** [comment]
Merged :) I'll make sure this gets in the next version.
