### ISSUE TITLE
Woo | CCF | and the Rest

### ISSUE THREAD

**Issue by BurlesonBrad** [tlovett1/custom-contact-forms#265]
I've pulled the latest [master from Woo](https://github.com/woothemes/woocommerce), and the latest master from[ CCF](https://github.com/tlovett1/custom-contact-forms).
Initially, I see this error:
`[05-May-2016 19:20:43 UTC] PHP Fatal error: Cannot declare class WP_REST_Controller, because the name is already in use in /home/faithera/public_html/wp-content/plugins/custom-contact-forms/wp-api/lib/endpoints/class-wp-rest-controller.php on line 4`

So I run `grep -r "WP_REST_Controller"` and, of course, I find this:

`./wp-content/plugins/woocommerce/includes/api/class-wc-rest-order-notes-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-order-notes-controller.php:class WC_REST_Order_Notes_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-customer-downloads-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-customer-downloads-controller.php:class WC_REST_Customer_Downloads_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-product-attributes-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-product-attributes-controller.php:class WC_REST_Product_Attributes_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-reports-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-reports-controller.php:class WC_REST_Reports_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-product-reviews-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-product-reviews-controller.php:class WC_REST_Product_Reviews_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-report-sales-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-report-sales-controller.php:class WC_REST_Report_Sales_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-webhook-deliveries.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-webhook-deliveries.php:class WC_REST_Webhook_Deliveries_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-tax-classes-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-tax-classes-controller.php:class WC_REST_Tax_Classes_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-customers-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-customers-controller.php:class WC_REST_Customers_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-taxes-controller.php: * @extends WP_REST_Controller
./wp-content/plugins/woocommerce/includes/api/class-wc-rest-taxes-controller.php:class WC_REST_Taxes_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-posts-controller.php:abstract class WC_REST_Posts_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-terms-controller.php:abstract class WC_REST_Terms_Controller extends WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/vendor/class-wp-rest-controller.php:abstract class WP_REST_Controller {
./wp-content/plugins/woocommerce/includes/vendor/class-wp-rest-controller.php: _doing_it_wrong( 'WP_REST_Controller::register_routes', 'The register_routes() method must be overriden', 'WPAPI-2.0' );
./wp-content/plugins/woocommerce/includes/class-wc-api.php: if ( ! class_exists( 'WP_REST_Controller' ) ) {`

Ok now, @tlovett1 and @westonruter,  you rocket ninja genius super stack grunting gulping vagrants that are CLI-ing the var while you REST are going to have to forgive me here as I'm still in the always-be-learning rabbit hole of code, but....

Doesn't this mean that if Woo is using the class name of `WP_REST_Controller,` then Custom Contact Forms can **NOT** try to come in and **"take over"** _(for lack of a better word)_, right?

So, anyone using Woo _(who happens to **HATE** cf7)_ won't be able to use both Woo and CCF? Surely that's not the case.  How do I find the fix?

**Comment by westonruter** [comment]
@BurlesonBrad It seems both of the plugins are bundling their own copies of the WP REST API plugin. That would be the problem.

**Comment by tlovett1** [comment]
I'm working on a fix for this. Stay tuned for something this week.

**Comment by BurlesonBrad** [comment]
whew! Thank 'ya @tlovett1 !! 
Ever seen a small-ville, busy dad of three, old man, sittin' in the dad chair try to peck away at a keyboard 'till a successful if / then statement (that works) suddenly pops into some type of functional code? 
![giphy 1](https://cloud.githubusercontent.com/assets/6208757/15063226/e8a72d30-130d-11e6-80be-c84fb8171842.gif)
I would've figured it out **.......eventually**

**Comment by tlovett1** [comment]
Fixed.
