### ISSUE TITLE
Captcha - Can it be added?

### ISSUE THREAD

**Issue by notbobj** [tlovett1/custom-contact-forms#28]
We would like this functionality. Could it be added somewhat easily? I really like this plugin but need captcha installed.
Thanks!

**Comment by tlovett1** [comment]
This will be in version 6.2. Right now it is in the develop branch here.

**Comment by notbobj** [comment]
Ok. Thank you!
Any ETA on that?
Thanks again!!
 
Date: Mon, 19 Jan 2015 14:00:06 -0800
