### ISSUE TITLE
nags

### ISSUE THREAD

**Issue by chuckreynolds** [tlovett1/custom-contact-forms#297]
upon install there's a new nag to signup for newsletter for tips and stuff.... i hit go away... then there's another one when managing a new form?

I've had this installed for a while now on a personal site to test and and like it, and now using for client sites but not into the nag divs. 

is there a filter to nuke those or should that one in manage form be off if the initial warning nag on install was removed?

**Comment by tlovett1** [comment]
There is a filter `ccf_hide_ads`. Just need to return true in that.
