### ISSUE TITLE
404 /wp-json/ccf/forms

### ISSUE THREAD

**Issue by r0n22** [tlovett1/custom-contact-forms#30]
Been trying to saving forms on my website from update.

I am getting a 404 on the json request.  

This might also be part of Issue #22.

**Comment by tlovett1** [comment]
Try updating permalinks? Make sure you are using pretty permalinks?

**Comment by r0n22** [comment]
You are 100% correct my pretty permalinks are being blocked by my provider I will close this for now until I resolve the issue on my end first.
