### ISSUE TITLE
Wordpress 4.7.1 Issue

### ISSUE THREAD

**Issue by georgewitteman** [tlovett1/custom-contact-forms#301]
Every time I open a page or post I get the error "Custom Contact Forms is experiencing issues.
There is an issue with synchronizing data. Please try the following:...". I have tried all the suggestions and am still getting this popup. I am also not able to see some of the forms. They show up in the list of forms, but when I click on them I am not able to see any submissions or edit the form.

**Comment by georgewitteman** [comment]
Issue seems to have resolved itself.

**Comment by webspilka** [comment]
look at your php.ini 
and try set 
```
always_populate_raw_post_data = -1
```
