### ISSUE TITLE
Coss Site Scripting Vulnerability

### ISSUE THREAD

**Issue by sathyavpk** [tlovett1/custom-contact-forms#303]
WPscan showing the plugin is vulnerable to cross site scripting

Screenshot: https://s27.postimg.org/oauwrhfc3/screenshot_2017_02_01_at_11_14_41.jpg
Vulnerability Info: https://wpvulndb.com/vulnerabilities/6296

**Comment by tlovett1** [comment]
That's for a version released years ago.
