### ISSUE TITLE
API is not protected in any way

### ISSUE THREAD

**Issue by Hrnkas** [tlovett1/custom-contact-forms#304]
I was able to get the form submissions without any kind of authentication, just by visiting the url http://www.mywebsite.com/wp-json/ccf/v1/forms/349/submissions/
I tried it using Incognito mode in Chrome and also using my cell phone browser (also a chrome).

Is there any official way to protect the api using some sort of authentication?
In the meantime I have to use rather unsecure http auth.

**Comment by cmmarslender** [comment]
@tlovett1 I was able to confirm this as well.
