### ISSUE TITLE
After new update...

### ISSUE THREAD

**Issue by WebGardenGeek** [tlovett1/custom-contact-forms#31]
I could use a little help fixing this issue...

This started after the update to the new CCF - don't have this problem on other sites, any ideas on what it could be? The site is under development (and has ultimate coming soon plugin activated for a splash screen), so I can't post a link that would be anything useful...

Parse error: syntax error, unexpected ')', expecting '&' or variable (T_VARIABLE) in /data/9/3/124/89/3776415/user/4196645/htdocs/fairwaysweb/wp-content/plugins/custom-contact-forms/classes/class-ccf-form-manager.php on line 815

Any ideas?

**Comment by WebGardenGeek** [comment]
<% field.choices.each( function( choice ) { %> 

this is the code that appears on line 815 of that php file...

**Comment by tlovett1** [comment]
What version of PHP are you running?

**Comment by WebGardenGeek** [comment]
Running PHP 5.5

**Comment by tlovett1** [comment]
Apache?

**Comment by tlovett1** [comment]
What host are you on?

**Comment by mikeyd08** [comment]
I am getting this same error message. We host with networksolutions with PHP 5.3.27

**Comment by mikeyd08** [comment]
Today I tried to update again and received the following:

Plugin could not be activated because it triggered a fatal error.
Fatal error: Only variables can be passed by reference in /data/15/2/131/51/2946866/user/3266404/htdocs/infosite/wp-content/plugins/custom-contact-forms/classes/class-ccf-form-manager.php on line 198

**Comment by theranchmine** [comment]
I also have the same issue since updating. I get this error when trying to activate the plugin again.

Fatal error: Only variables can be passed by reference in /hermes/waloraweb003/b1548/moo.theranchminecom/wp-content/plugins/custom-contact-forms/classes/class-ccf-form-manager.php on line 198

**Comment by WebGardenGeek** [comment]
Updated again and now this is the error I'm getting (which seems to be the same as the comment above)

Fatal error: Only variables can be passed by reference in /data/9/3/124/89/3776415/user/4196645/htdocs/fairwaysweb/wp-content/plugins/custom-contact-forms/classes/class-ccf-form-manager.php on line 198

and sorry, I was wrong about the PHP version before. This site is also hosted on Network Solutions, which runs PHP 5.3.27 and I have not found a way to update to PHP 5.5 via the hosting tools they allow their customers to configure.

**Comment by mikeyd08** [comment]
So, is the problem the version of PHP? Are the server requirements for this plugin listed anywhere?

**Comment by tlovett1** [comment]
This is fixed in 6.3.2

**Comment by WebGardenGeek** [comment]
Thank you Taylor - awesome work!

**Comment by theranchmine** [comment]
Thank you so much Taylor, much appreciated!

**Comment by mikeyd08** [comment]
Thanks very much! 


Mike Davis
MTBW Services, Inc.
www.mtbw.com
327 Ridgeville Blvd #154
Mt. Airy, MD 21771
voice: 301-829-5925 x250
Fax: 301-829-5923
mdavis@mtbw.com


______________________________________________
