### ISSUE TITLE
form stopped showing

### ISSUE THREAD

**Issue by ozpod** [tlovett1/custom-contact-forms#34]
hi, i created a wp site for a friend,  and about 2 years ago i set up a custom contact form for her on a page of the site.

everything was fine until about 2 months when the form just disappeared from the page.   I literally haven't done anything to the site or even gone into the admin area for over a year,  so i've changed nothing on the site that could have done this.

i have just now updated to the latest wp version and to the latest custom contact form version,  but the form is still not showing.

can you please tell me where i can find my old form (can't find it anywhere) and how do i get it to show on the page again?

thank you!

**Comment by tlovett1** [comment]
You will need to upgrade your DB (you should have been prompted to do this). You may also need to rebuild the form.

**Comment by ozpod** [comment]
how do i upgrade the db?  instructions please
