### ISSUE TITLE
code breaking

### ISSUE THREAD

**Issue by olyfaunt** [tlovett1/custom-contact-forms#35]
![screen shot 2015-01-24 at 12 08 18 pm](https://cloud.githubusercontent.com/assets/7607614/5888785/c7240474-a3c1-11e4-8f97-1d89eecb0a3f.png)
http://www.abcacademicbooks.com/contact-abc/

Not sure why
 <span class="tc-update-notice label label-default">Recently updated !</span>
is showing up..

Also I get the above view if I'm signed into WP admin..

**Comment by tlovett1** [comment]
This is fixed. It will be pushed into the next version. Feel free to use the development version from Github until then. Thank you!
