### ISSUE TITLE
checkbox/radio buttons/dropdown issue 

### ISSUE THREAD

**Issue by kgolear** [tlovett1/custom-contact-forms#36]
Validators seem fixed as of now, and form "sends" but still delivering no results in the email notifications. The notifications send a 'zero' or a blank, no matter what was selected in the form when sent.

**Comment by tlovett1** [comment]
Can you post a link to the form?

**Comment by kgolear** [comment]
I have re-created a test page and test forms here:  http://massageofdallas.com/form-testing-page/

**Comment by tlovett1** [comment]
Hmm I just received notification emails that look fine.

**Comment by kgolear** [comment]
Yes-you helped me solve earlier today.  (I needed to put values!)  Thank
you again.
Karen

On Thu, Jan 29, 2015 at 4:26 PM, Taylor Lovett <notifications@github.com>
wrote:

> Hmm I just received notification emails that look fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tlovett1/custom-contact-forms/issues/36#issuecomment-72117049>
> .
>



-- 
Karen O'Leary
214-682-2930
http://www.lgwebandgraphic.com/
http://www.lgwebandgraphic.com/smb-blog
