### ISSUE TITLE
{{ label }} After Update

### ISSUE THREAD

**Issue by klrmac** [tlovett1/custom-contact-forms#38]
This is all I'm seeing on my forms and form creation after recently updating to Version 6.3.2.

Any assistance ASAP would be appreciated. 
![contactform](https://cloud.githubusercontent.com/assets/10702186/5894714/202b1b8e-a4da-11e4-890d-080da90e9422.PNG)

**Comment by tlovett1** [comment]
Can you try deactivating other plugins and activating a default theme to see if you have a conflict?
