### ISSUE TITLE
Cannot edit existing forms

### ISSUE THREAD

**Issue by vanessa-p** [tlovett1/custom-contact-forms#39]
Hi,

After updating the plugin and database, we were able to retrieve some of the old forms on our site. However, when I tried to edit the form, it only saves in the Manage Forms window. The form does not update in the preview mode or in the actual post.

A second issue I notice is that if I create a new form from the dashboard (not in a post), it will be saved as "Scheduled" instead of Published. Therefore, when I start a new post and try to add the form, it will not show up in the existing forms list.

Then I tried creating a new form in the post, I can't drag and drop the field into the form. 

Could you please let me know why any of these might have happened, any suggestion to fix?

This is on WP 4.0.1. I updated CCF to version 6.3.2. Sorry for the long post, I really want this to work as so far it's the best form plugin we have found.

**Comment by ginestra** [comment]
I'm having the same issue. Any help is very much appreciated. Thanks.

**Comment by tlovett1** [comment]
Have you tried deactivating other plugins and activating a default theme to check for conflicts?

**Comment by vanessa-p** [comment]
Hi Taylor,

It seems that when I update the plugin to 6.3(?) yesterday, it fixes the
saving issues, so no worries.

Thank you though for responding.

Have a great day!



Sincerely,

*Vanessa Pham*
Marketing Associate
*Sense Financial Services LLC*
*Retirement Accounts with Checkbook Control*
Email: vanessa@sensefinancial.com <maria@sensefinancial.com>
Web: www.SenseFinancial.com <http://www.sensefinancial.com/>
Direct: (949) 228-9450


[image: Facebook] <https://www.facebook.com/SenseFinancial>  [image:
LinkedIn] <http://www.linkedin.com/company/sense-financial-services-llc>
 [image:
Twitter] <https://twitter.com/sensefinancial7>  [image: Google+]
<https://plus.google.com/+Sensefinancial/about>

<http://www.sensefinancial.com/>

**Comment by tlovett1** [comment]
Great!
