### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by davissm** [tlovett1/custom-contact-forms#40]
My Custom Contact Form Plugin stopped emailing notifications a couple of months ago, perhaps after a recent upgrade. I have seen an option to update the database and did execute that option after a recent upgrade. Still, am not receive email notifications using wordpress default option.

Best,
Steve

**Comment by tlovett1** [comment]
Are you receiving WordPress "Lost Password" emails?

**Comment by davissm** [comment]
No, not receiving any.

 

This system is working fine on a couple other sites of mine. So perhaps this
involves a conflict with another plugin. I thought it might be with a new
captcha plugin I started using a couple months ago but had same problem when
I disabled it.

**Comment by tlovett1** [comment]
If you aren't receiving WP mail at all (lost password as an example), the plugin notification emails will definitely not work.

**Comment by davissm** [comment]
Hi Taylor,

 

Even with your latest version installed, the comments in the submission
field is getting cut off so I can't read but the first few words of the
message. Are you aware of this issue?

 

Best,

Steve

 

 
<http://t.signalequattro.com/e1t/o/5/f18dQhb0S7ks8dDMPbW2n0x6l2B9gXrN7sKj6v4
fhf4N3M2sqlQByLCW641J8j4PCG21f43K7KH01?si=4786657887256576&pi=4222e616-806f-
4a72-a188-b08601e4fa00>

**Comment by tlovett1** [comment]
Yes, if you click the "eye" icon you will see the full submission.

**Comment by davissm** [comment]
Hi Tyler,

 

I don't see an "eye" icon anywhere but there is an active area to at end the
table row that doesn't do anything when I click it. Any ideas?

**Comment by tlovett1** [comment]
Can you take a screenshot?

**Comment by davissm** [comment]
Yes. Image is attached.  I can click on the link to display the message even
though icon does not appear, but display simply dims and nothing is
displayed.

**Comment by tlovett1** [comment]
Image is not showing up :/

**Comment by davissm** [comment]
Here it is below

**Comment by tlovett1** [comment]
Not seeing it.... Please post a link directly via Github.

**Comment by davissm** [comment]
Here you go:

http://facilitatoru.com/CCF%20Image.jpg
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX48
p-_cWW65jsHg8qm3CRF7_Kd49hBfTf6Jl7gj03?t=http%3a%2f%2ffacilitatoru.com%2fCCF
%2520Image.jpg&si=4786657887256576&pi=3e0c83f3-cb8e-4c9f-86bf-75fc8237b726>

**Comment by tlovett1** [comment]
@davissm seems like a CSS issue. I would try to deactivate other plugins and activate a default theme to see if something else is doing that.

**Comment by davissm** [comment]
Probably is a theme issue as plugin continues to work on other themes/sites
I'm running.

 

And Deactivating plugins alone didn't do it on this site.

 

Thx

steve
