### ISSUE TITLE
Long field descriptions/instructions

### ISSUE THREAD

**Issue by vanessa-p** [tlovett1/custom-contact-forms#41]
Hi Taylor, 

The updated version works well for us now.

What we miss from the old version was the field option(?) where we can leave field descriptions or instructions. We are using CCF for an application form which have some long instruction for a field. Before, with the "popup" field instruction, the length is not a problem. In the new version, however, we have nowhere to put it, the placeholder text doesn't offer enough space. The long message is cut off and users will not be able to to see the full instruction.

Could you perhaps look into this please? Maybe bring back the popup field option? 

Thank you!

**Comment by tlovett1** [comment]
I'll definitely look into this. Thanks for the tip!

**Comment by tlovett1** [comment]
"Field Description" has been added to version 6.4. Thanks!
