### ISSUE TITLE
Upgrading from pre 6.0

### ISSUE THREAD

**Issue by jeathree** [tlovett1/custom-contact-forms#42]
"Note: Version 6.0 breaks backwards compatibility. You will need to perform a database update after upgrading from anything pre 6.0. You may also need to reconfigure some of your forms."

Is there more information somewhere on how to do this?

I recently upgraded from pre 6, my forms show up on the frontend but are not listed to view or edit in the admin.  They also don't send anymore.

**Comment by tlovett1** [comment]
Did you see the upgrade notice?

**Comment by jeathree** [comment]
The upgrade notice I quoted in my question?  

Yes, I seen it.  It's very vague.  Do a database upgrade and reconfigure some of your forms, I was asking for more details on these items.

**Comment by tlovett1** [comment]
Clicking upgrade will convert all your forms to the new data storage methods. There is not a 1:1 mapping of old features to new features so it's possible certain fields will need manual clean up. Upgrade will not delete old data so you can always revert to an old version of the plugin. Does that help?

**Comment by tlovett1** [comment]
Ah no I misunderstood. You should be prompted to upgrade within your WordPress admin.
