### ISSUE TITLE
Drop Downs, Radios no longer work correctly. 

### ISSUE THREAD

**Issue by Gateruner** [tlovett1/custom-contact-forms#44]
Since the update the drop down/radios/check boxes menus do not function correctly. When I reset the dropdown it shows up on the form completely open. I could live with that if it worked. When you make the dropdown a required item it does not recognize that you have made a choice when you try to submit the email. It keeps telling you that you have to make a choice when a choice has been made. Another issue that I ran across is when you add the "phone" option from the special fields list. When submitting an email, if you added the - to the phone number the form gives an error that says there is to many numbers. Not a huge issue as I just used the Text Line option. Finally, is it possible to specify the font color in the message box. It is printing black and in my theme the box is brown so it barely shows up for the user. Strangely the text in all the other boxes are white. 

Thanks for any help you can give me.,

**Comment by tlovett1** [comment]
You need to specify a "value" for the field option otherwise it will not be recognized as a choice.

I will take a look at the phone bug.

To change the color of the text box, you will need to use CSS in your theme.

**Comment by Gateruner** [comment]
Ok stupid question on my part. What is the value that needs to be put in the box. I tried to find something that said what it was but did not see anything about what to actually enter for the value. 
 

     On Thursday, February 5, 2015 10:32 AM, Taylor Lovett <notifications@github.com> wrote:
   

 You need to specify a "value" for the field option otherwise it will not be recognized as a choice.I will take a look at the phone bug.To change the color of the text box, you will need to use CSS in your theme.—

**Comment by tlovett1** [comment]
You can just put the same thing in value as the label.

**Comment by Gateruner** [comment]
Got it thanks

Sent from Scott's IPhone
Scott Caffrey
Caffrey's Photography
281-799-7596
email: scott@caffreysphotography.com
