### ISSUE TITLE
Form Widget

### ISSUE THREAD

**Issue by robneu** [tlovett1/custom-contact-forms#46]
I'd love to migrate some sites over to this plugin, but the lack of a widget is a bit of a deal breaker in a lot of situations. Is this something you'd prefer to see in an add-on or are there plans to add one at some point?

**Comment by tlovett1** [comment]
Expect this to be added in the next version. It's a pretty simple thing to write.

**Comment by robneu** [comment]
Sweet! :100:

**Comment by tlovett1** [comment]
This has been added to 6.4
