### ISSUE TITLE
file upload gone? and constantly asking me to update

### ISSUE THREAD

**Issue by sjulau** [tlovett1/custom-contact-forms#47]
Hi! I love this plugin, but it seems the file uploader on my form is gone now. I'm not sure how to get it back on, can you help?

I keep being asked to update, I update, I get taken to a page with what could be arabic writing and then I go back and then it asks me to update again. So I'm not sure what to do to fix this, thanks!!

**Comment by tlovett1** [comment]
File uploads have been added to 6.4
