### ISSUE TITLE
"Add Form" button not functioning

### ISSUE THREAD

**Issue by LovesChachi** [tlovett1/custom-contact-forms#48]
Hi,
I'm having trouble with the new "Add Form" button. When I click it, nothing happens. Can you help me figure that out?

Or is there another way to access a shortcode to place into a page?

Thanks!

**Comment by tlovett1** [comment]
Have you tried deactivating other plugins? What theme are you using?

**Comment by LovesChachi** [comment]
I'm using Bridge theme 5.0. site: joaniecahill.com

I haven't tried deactivating any other plugins, are there some I should?

**Comment by tlovett1** [comment]
Can you try deactivating all other plugins and activating a default theme like TwentyFifteen?

**Comment by AZ138** [comment]
I am having this same problem. I tried deactivating all other plugins and activating TwentyFifteen but no luck. Any other recommendations?

**Comment by tlovett1** [comment]
Just tried the Make theme with version 4.1.1. "Add Form" worked fine.

**Comment by AaronHolbrook** [comment]
I can confirm - this works fine for me (WP 4.2-alpha, Twenty Fifteen theme, no plugins).

@AZ138 what version of PHP are you running on? Can you try this on a vanilla installation (fresh install / clean database)?

**Comment by AZ138** [comment]
I have it working with 2015 now. My site only has one form so not a big deal. Thanks for the replies!
