### ISSUE TITLE
any chance to add option to limit the Date selection

### ISSUE THREAD

**Issue by chiangchiheng** [tlovett1/custom-contact-forms#50]
Hello

I wanna use CCF as a booking form

I want the date field selection can be limited into a specific range (e.g. can only select 7 days later and within a month)

is it possible to do that

thank you

**Comment by tlovett1** [comment]
This might be possible through clever hooking but is not supported by the plugin explicitly.

**Comment by chiangchiheng** [comment]
Hello

I guess that mean someone has to write another plugin for the function I mentioned.
but right now it's not possible to built that in

thank for reply

I will keep my searching

thanks again
