### ISSUE TITLE
CAPTCHA not functioning

### ISSUE THREAD

**Issue by sonikamadarasmi** [tlovett1/custom-contact-forms#51]
The CAPTCHA disappears sometimes, and then the form can't be submitted because it's a required field. Sometimes a refresh of the page is needed but that doesn't work all the time.

**Comment by tlovett1** [comment]
Can you link to the form?

**Comment by webstractions** [comment]
This may have something to do with a similar question on the WP.org forums at https://wordpress.org/support/topic/recaptcha-issues-1?replies=17

There is not a fallback for the plugin to use the old-fashioned captcha form, plus it appears that the new form is a little buggy when it comes to IE (any version).

It could also be a float-clearing problem for the wrapper (.ccf-recaptcha-wrapper), which causes the 'send' button to appear above the form itself, and I suspect may be hiding the form as the poster above may be experiencing.

**Comment by tlovett1** [comment]
Can you link to a problematic form?

**Comment by sonikamadarasmi** [comment]
Dear Taylor

I fixed it I just had to redo the form and it's working.

Thanks!

Sonika

Sonika Madarasmi's Iphone
