### ISSUE TITLE
Unable to remove submissions

### ISSUE THREAD

**Issue by vanessa-p** [tlovett1/custom-contact-forms#52]
Hi,

After upgrading the database, we have many duplicated submissions on some forms. We'd like to clean up the duplicated entries and also remove the ones that we created as a test.

However, the delete button doesn't seem to work. It didn't do anything after I clicked on it. The "eye" button next to it works perfectly, showing the submissions without any issue.

Could you please give us some suggestion to why this is and how to fix it?

Thank you!

**Comment by tlovett1** [comment]
Can you try deactivating other plugins and activating a default theme to see if it's a conflict? Can you send the network requests? There is probably a JS error.

**Comment by vanessa-p** [comment]
How do I send the network requests?

**Comment by CCCTina** [comment]
I have just updated to version 6.4.1 and have the same issue. The "X" does not work to delete within WordPress.

**Comment by tlovett1** [comment]
Both of you:

Can you try deactivating other plugins and activating a default theme to see if it's a conflict?

Also, right click and click inspect, then go to the network tab to see network requests.
