### ISSUE TITLE
file upload not working

### ISSUE THREAD

**Issue by jellebelly** [tlovett1/custom-contact-forms#53]
Just updated plugin & recreated forms.  Our simple Contact form is working perfectly.  The "request bid" form, where the user can upload a pdf, jpg, gif, or png LOOKS like it's uploading the file, but the email is received with all info except the attachment.  No errors appear and the form looks like it all has all worked perfectly.  what am I doing wrong?
here's a test page:
http://www.cascadebuildingcomponents.com/testpage/
thanks

**Comment by jellebelly** [comment]
![jumpchairs](https://cloud.githubusercontent.com/assets/11000577/6197801/4700b00e-b3a1-11e4-9666-16f5ec280712.jpg)
Here's a screenshot of a sample email

**Comment by CCCTina** [comment]
I just updated to 6.4.1 and am having the same problem.  This is the message that comes through in the contact submission emailed to me.
Warning: stripslashes() expects parameter 1 to be string, array given in /home/creati47/public_html/wp-content/plugins/custom-contact-forms/classes/class-ccf-form-handler.php on line 750

**Comment by tlovett1** [comment]
What browser are you using to test the form?

**Comment by jellebelly** [comment]
Chrome Version 40.0.2214.111 m  

But I also tried with the latest version of IE and with IE I get a weird error where it tries to open a .js file with visual studio software installed on my computer.  And form is never sent.

 

IE error: asks if I want to open or save admin-ajax.json from (my domain) and when I open, I see this:

{"success":true,"action_type":"text","completion_message":"Thanks! We'll get back to you as soon as possible."}

**Comment by CCCTina** [comment]
I have tried Mozilla 33.0.2, IE 11.0.9600.17633, and Chrome 40.0.2214.111.
The checkbox issue does not work for any of them.
I only tested file upload and deletion of submissions on WordPress with
Chrome.
Tina

**Comment by CCCTina** [comment]
Thank you.  The file upload is working well now.
