### ISSUE TITLE
Checkboxes not working when set as a requirement

### ISSUE THREAD

**Issue by CCCTina** [tlovett1/custom-contact-forms#55]
I have a field with three checkboxes.  When I have it set as a requirement that the submitter must choose at least one, upon submitting the form, it thinks that the data is missing and won't submit.  If I turn off the requirement, the submission will go through, but the field is empty in the submission form for any amount of boxes checked.  This field was working until I updated to version 6.4.1.
Thank you.

**Comment by tlovett1** [comment]
Do your checkboxes have values set?

**Comment by CCCTina** [comment]
Yes and they were working until I did the most recent upgrade.
Tina

On Feb 18, 2015, at 9:45 AM, Taylor Lovett <notifications@github.com> wrote:

Do your checkboxes have values set?

—
Reply to this email directly or view it on GitHub
<https://github.com/tlovett1/custom-contact-forms/issues/55#issuecomment-74874848>
.

**Comment by tlovett1** [comment]
Can you link me to the form?

**Comment by CCCTina** [comment]
My website link is:  http://www.creativecakeco.com/contact.html

The email I receive is copied below.  It used to email as '0 custom cake, 1
custom cupcakes, or 2 decorated sugar cookies' depending upon what was
checked.  In this test, I checked cake and cookies and it shows a '-'.
*Name (Name):*
Tina S
*Email (Email):*
Tina@CreativeCakeCo.com
*Phone (Phone):*
4843691772
*Date of Event (Date-Time):*
2/28/2015 06:00 pm
*Type of Event (Event-Type):*
birthday
*Dessert(s) of Interest (Desserts):*
-
*Number of servings needed (Servings):*
50
*Inquiry (Inquiry):*
test
*How did you hear about us? (Referral):*
Google search
Form submitted from: http://www.creativecakeco.com/contact.html
