### ISSUE TITLE
Can't save changes

### ISSUE THREAD

**Issue by enelam** [tlovett1/custom-contact-forms#56]
Hi there,
I can make the changes all good and I click the Save Changes button, but when I look at the form again it is not saved.
I saw someone saying to Replace all occurrences of /ccf/forms with ccf/forms in the form-manager.min.js file, but that does not work.

Help please

**Comment by tlovett1** [comment]
Can you check for plugin/theme conflicts by deactivating other plugins and activating a default theme?

**Comment by enelam** [comment]
thank you so much.. that worked :-)
It was not the theme (OptimizePress) it was one of the plugins.
Thanks again.

**Comment by tlovett1** [comment]
Happy to help! Please leave a positive review on WP.org.

**Comment by enelam** [comment]
Done.
Thanks

Kind Regards,
Malene Holm
