### ISSUE TITLE
IE11 “Do you want to open or save admin-ajax.json”

### ISSUE THREAD

**Issue by JanickMantov** [tlovett1/custom-contact-forms#58]
Hi there

I installed your plugin and tried to make forms work - here I made a simple form with a single standard paragraph text and the Form Settings button.

I get the error message “Do you want to open or save admin-ajax.json” in IE11 - the form works just fine in Chrome and Firefox.

![ie11-openorsave_admin-ajax json](https://cloud.githubusercontent.com/assets/8946765/6225652/9255eaa8-b68d-11e4-8f4d-df8b8a5e37a0.jpg)

Thanks for the nice work
Janick

**Comment by tlovett1** [comment]
This is fixed.
