### ISSUE TITLE
Error when selecting "Pull "From" Email Dynamically from Field"

### ISSUE THREAD

**Issue by superiorus** [tlovett1/custom-contact-forms#59]
It was working fine, but after the upgrade to 6.4.1  is not working.

I need this because I must reply to my client email.

Any help please ?

Image attached for detailes 

![error plugin](https://cloud.githubusercontent.com/assets/11059834/6247455/6ac03a20-b77d-11e4-986e-930a1991dc59.jpg)

**Comment by superiorus** [comment]
also the "email" field  from plugin admin panel is empty.

**Comment by tlovett1** [comment]
Will look into this shortly. Thanks!

**Comment by tlovett1** [comment]
Does the email field have a slug? What browser are you using?

**Comment by superiorus** [comment]
I use Chrome and it give the error.
Also tested with IE and is working well. (it shows)

**Comment by tlovett1** [comment]
Are there any errors in the web inspector console? I'm not able to reproduce.

**Comment by superiorus** [comment]
I dont have the skills to work with inspector console ...

The issue is : in Chrome I can't select the email field (see the attached
picture)

On Wed, Feb 18, 2015 at 10:18 PM, Taylor Lovett <notifications@github.com>
wrote:

> Are there any errors in the web inspector console? I'm not able to
> reproduce.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tlovett1/custom-contact-forms/issues/59#issuecomment-74939605>
> .
>



-- 
► Put your website/business on the 1-st page in Google and Bing, promote it
on Facebook !
Buy Google Adwords, Facebook Ads, Bing Ads coupons at low prices. :
http://voucherstore.net

**Comment by tlovett1** [comment]
Can you email me at tlovett88 [a] gmail?
