### ISSUE TITLE
Email notification customization

### ISSUE THREAD

**Issue by gustochris** [tlovett1/custom-contact-forms#60]
Hello,

I'm trying to determine how to customize the email notification.  This includes the actual email, the from name and the subject line.  Any help as to what files I could edit to accomplish this would be greatly appreciated.

**Comment by tlovett1** [comment]
You can filter `ccf_email_content` which is on line 803 of `includes/class-ccf-form-handler.php`

Hope that helps!

**Comment by gustochris** [comment]
Thank you!
