### ISSUE TITLE
Upgrade: An unknown error occured.

### ISSUE THREAD

**Issue by gustochris** [tlovett1/custom-contact-forms#61]
I've upgraded and now get this error.  I double checked by deactivating, deleting all files and then reinstalling the plugin from scratch.  Now I get "An unknown error occured." When I click submit on my form.

Any help? The emails are still coming through, it's just the front side is stuck,

**Comment by gustochris** [comment]
I upgraded to get rid of the IE json file download bug

**Comment by tlovett1** [comment]
Can you link to the form?

**Comment by gustochris** [comment]
Thank you very much for your help but I've moved toward another solution.
