### ISSUE TITLE
font colour

### ISSUE THREAD

**Issue by sirclive** [tlovett1/custom-contact-forms#62]
For some reason the font colour on my form has changed to white on a white background (may have been due to a theme update). Is there an easy way for me to change the font colour on my form back to black? Am sure this is a simple thing but I can't find it.

**Comment by tlovett1** [comment]
You will need to add CSS to your theme. CCF tries to by styling agnostic (for the most part).

**Comment by sirclive** [comment]
Ah I feared as much. CSS is all french to me.
