### ISSUE TITLE
No notifications  are send to my emailadress?

### ISSUE THREAD

**Issue by goseo** [tlovett1/custom-contact-forms#63]

**Comment by zeeshan-999** [comment]
did you get any response on this, I am facing similar issue.

**Comment by goseo** [comment]
Nope. No response wat ever. 


Verzonden vanaf mijn Samsung-apparaat


-------- Oorspronkelijk bericht --------
Van: zeeshan-999 <notifications@github.com> 
Datum: 20-02-2015  12:23  (GMT+01:00) 
Aan: tlovett1/custom-contact-forms <custom-contact-forms@noreply.github.com> 
Cc: goseo <patrick@goseo.nl> 
Onderwerp: Re: [custom-contact-forms] No notifications  are send to my
  emailadress? (#63) 

did you get any response on this, I am facing similar issue.

**Comment by tlovett1** [comment]
CCF uses the default WP mail functionality. Is WP able to send lost password emails? If not, then you have a problem with your servers mail setup.

**Comment by goseo** [comment]
WP send lost password emails. I use the contact plugin on a subdomain. nieuw.goseo.nl. maybe this is the problem. ? Setting problem of the plugin?

 

Van: Taylor Lovett [mailto:notifications@github.com] 
Verzonden: vrijdag 20 februari 2015 15:38
Aan: tlovett1/custom-contact-forms
CC: goseo
Onderwerp: Re: [custom-contact-forms] No notifications are send to my emailadress? (#63)

 

CCF uses the default WP mail functionality. Is WP able to send lost password emails? If not, then you have a problem with your servers mail setup.

**Comment by zeeshan-999** [comment]
Mine is working now.i had to setup MX settings on my domain. If your mail server is not setup this could also be the reason


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: goseo <notifications@github.com> </div><div>Date:21/02/2015  13:15  (GMT+04:00) </div><div>To: tlovett1/custom-contact-forms <custom-contact-forms@noreply.github.com> </div><div>Cc: zeeshan-999 <zeeshan-999@hotmail.com> </div><div>Subject: Re: [custom-contact-forms] No notifications  are send to my emailadress? (#63) </div><div>
</div>
WP send lost password emails. I use the contact plugin on a subdomain. nieuw.goseo.nl. maybe this is the problem. ? Setting problem of the plugin?



Van: Taylor Lovett [mailto:notifications@github.com]
Verzonden: vrijdag 20 februari 2015 15:38
Aan: tlovett1/custom-contact-forms
CC: goseo
Onderwerp: Re: [custom-contact-forms] No notifications are send to my emailadress? (#63)



CCF uses the default WP mail functionality. Is WP able to send lost password emails? If not, then you have a problem with your servers mail setup.

—
Reply to this email directly or view it on GitHub <https://github.com/tlovett1/custom-contact-forms/issues/63#issuecomment-75247422> .  <https://github.com/notifications/beacon/AKkF5ypzvmz4zHTVYOKkW7voEnd5aazFks5ntz5KgaJpZM4DixE9.gif>



---
