### ISSUE TITLE
reCAPTCHA not loading properly

### ISSUE THREAD

**Issue by BlackthorneMedia** [tlovett1/custom-contact-forms#64]
When I add the reCAPTCHA field to the form and enter the keys, it look OK until I navigate away from the form. Once saved the reCAPTCHA field disappears and is replace with a text field that says "Enter the numbers".

Now, I cant even remove the text field. Its not there in the Manage Form dialog box, but the field is still showing on the site.

Fully updated, running latest WP and Plugin. I ahve Bulletproof security running on this site. Could that be an issue?

FYI the form worked for a while, then stopped working after a WP update.

**Comment by tlovett1** [comment]
Are there any JavaScript errors on the page? Do you have a caching plugin setup? Can you link me to the form?

**Comment by BlackthorneMedia** [comment]
No errors I can see. I ma in the WP dashboard and managing inside the plugin.

As far as I know we do not have any caching plugins.

Form is on http://www.cerps.ca/contact/

**Comment by BlackthorneMedia** [comment]
I can give you access if you need to see the error from the dashboard side.

**Comment by tlovett1** [comment]
Can you email me tlovett88 [at] gmail
