### ISSUE TITLE
Email notification not sent 

### ISSUE THREAD

**Issue by zeeshan-999** [tlovett1/custom-contact-forms#65]
No email notification is sent to the email I specified in the fields for notification,.
I can see the form is submitted in the submissions but no notification via email at all.

**Comment by AaronHolbrook** [comment]
Are you able to send email from your WordPress instance? Try sending a 'lost password' email to yourself to ensure that email sending works correctly.

Do you possibly have any email sending plugins that are affecting the sending of email?
