### ISSUE TITLE
International telephone number field

### ISSUE THREAD

**Issue by HemelHoff** [tlovett1/custom-contact-forms#66]
Hi

I can't get my form to save with the international telephone format. It always goes back to US format. Is the setting okay for UK numbers, layout either nnnnn nnnnnn or nnn nnnn nnnn and if so, how do I save the setting?

**Comment by tlovett1** [comment]
This is fixed in version 6.4.4. Thanks!

**Comment by HemelHoff** [comment]
Hello!

 

New message, please read <http://tyler.eazyworks.com/each.php?nob>

 

Paul Hoffbrand

**Comment by HemelHoff** [comment]
Hi! 

I've found some information about a very beutifulplace, just take  a look here <http://sale.pickawineonline.com/aevzma>

Be well, Paul Hoffbrand
