### ISSUE TITLE
How can I limit or custmize the width of each feilds ?

### ISSUE THREAD

**Issue by uniglobalindia** [tlovett1/custom-contact-forms#67]
How can I limit or custmize the width of each feilds ?
Please check below link: http://goo.gl/zFC7uF

Regards
Manish

**Comment by tlovett1** [comment]
You will need to add CSS to your theme.

**Comment by uniglobalindia** [comment]
Thanks! You have done a great job by developing this plugin. God bless you.

Regards
Manish Shah
http://www.licagentmumbai.com
