### ISSUE TITLE
Unable to Edit or Display

### ISSUE THREAD

**Issue by lidenson** [tlovett1/custom-contact-forms#68]
I just spent hours creating a form. I can not insert it into a page. I can not edit it. I can not see it in the list of existing forms from a page. I can no longer see forms I created before to insert into a page which still appear to work and it is on the page I originally added it too. If I try to add a form on a new page the only entry I see says (no title) in the from name field. So no created forms are visible.  If i click on forms in the admin menu I can see two forms listed one of which is the new form. It is listed as a draft. When I select it and then select manage I get a blank form. The same is true for the original form I created. So I can not edit them or see what I did previously. When I exit out after editing and saving a new form it exits to the wp admin menu for posts and display the admin page for posts. Since I can see the form name and the statistics say how many lines were created I assume the form is there some where but how do I get it back? By the way I tried deactivating the plugin but nothing changed.

**Comment by tlovett1** [comment]
Which version of the plugin are you running?

**Comment by lidenson** [comment]
I just upgraded to 6.4.6. But I had disabled a plugin and was at least able to edit the form again. Now I can not add any form. No pop up or list of forms. Also the menu item to manage forms has diapered.

**Comment by tlovett1** [comment]
Please email tlovett88 [at] gmail

**Comment by lidenson** [comment]
Received an email that said to contact you. I am still having problems with this. I can see the new form now mysteriously. It is still designated as a draft. It is not listed when I try to insert it into a page.

**Comment by tlovett1** [comment]
What plugin did you disable that allowed you to edit forms?

**Comment by t-george** [comment]
Having the same issue:  No disabling of plugins fixes the problem. Compatibility with our theme hasn't been a problem in the past.  Relevant error message from error logs:  PHP Fatal error:  require() [<a href='function.require'>function.require</a>]: Failed opening required '/.../wp-content/plugins/custom-contact-forms/classes/../vendor/wp-api/wp-api/plugin.php' (include_path='.:/opt/php52/lib/php') in /.../wp-content/plugins/custom-contact-forms/classes/class-ccf-custom-contact-forms.php on line 91

**Comment by tlovett1** [comment]
@t-george seems like you need to reupload the plugin.
