### ISSUE TITLE
reCaptcha not showing up in front end

### ISSUE THREAD

**Issue by assadnazar** [tlovett1/custom-contact-forms#69]
I have a form located at http://beta.consultfinman.com/register-for-a-course/ and the recaptcha is not showing up at all.
But in admin panel when i preview the form, it does show the recaptcha. What can be the issue?
There are no errors if i turn WP Debug on.

**Comment by tlovett1** [comment]
What version of the plugin is this? The recaptcha JS isn't included in the page.

**Comment by assadnazar** [comment]
Its the latest version from WP plugin directory "Version 6.4.6".
Can you guide me how to include the recaptcha JS into the pages?

**Comment by tlovett1** [comment]
Can you email tlovett88 [at] gmail
