### ISSUE TITLE
most browsers progress icon keeps spinning

### ISSUE THREAD

**Issue by joycemedia** [tlovett1/custom-contact-forms#70]
I am having an issue where the progress icon keeps spinning and no result is shown on form submission even though the mail is properly sent.

can you help?
thank you.

g

**Comment by tlovett1** [comment]
Can you post a link to your form?

**Comment by joycemedia** [comment]
sorry:   https://cwonj.com/join-cwonj/

**Comment by tlovett1** [comment]
Form worked fine for me. Which browser are you using?

**Comment by joycemedia** [comment]
i upgraded to a newer theme. Hoping it may have solved the issue.

thanks

g
On Feb 25, 2015, at 10:12 AM, Taylor Lovett <notifications@github.com> wrote:

> Form worked fine for me. Which browser are you using?
> 
> —
> Reply to this email directly or view it on GitHub.
> 












g

Regards,

George Edgar Joyce III
JoyceMedia
(856)455-3722
info@joycemedia.com
http://www.joycemedia.com
