### ISSUE TITLE
Custom Contact Forms is experiencing issues.

### ISSUE THREAD

**Issue by colin396** [tlovett1/custom-contact-forms#72]
Just completed update and now get this message!

Custom Contact Forms is experiencing issues.
There is an issue with synchronizing data. Please try deactivating all other plugins and activating the TwentyFifteen theme. If this fixes the problem, you have a plugin or theme conflict

**Comment by tlovett1** [comment]
What happens if you follow the instructions?

**Comment by colin396** [comment]
I did follow the instructions - Doesn't work in TwentyFifteen theme.
It has worked for months with the currently installed plug ins - error message only appeared after the latest upgrade. - Form still shows on site but getting error message

**Comment by tlovett1** [comment]
Please email tlovett88 [at] gmail

**Comment by FilipVandePeer** [comment]
Dear t, 

	I use your Custom Contact Form with great satisfaction, but since yesterday one of my Forms just didn’t work anymore. 

I cloned another one to adapt, but neither the clone wanted te show up.

So I created the Form from scratch, which is online again, but I now see that neither of my Forms redirect after pushing the submit button.
The redirect function worked properly before the latest update.

Any help?

Thanks in advance.

**Comment by FilipVandePeer** [comment]
In addition: it's not only the redirect that doesn't work anymore. Neither does the 'Show text' option of the 'on Form Completion'.

This really is quite problematic.

Thanks, 
      Filip

**Comment by FilipVandePeer** [comment]
Ok Taylor. 
Thanks for helping. 

Filip Van de Peer
GSM: 0478/58.70.43
