### ISSUE TITLE
Issues adding forms to pages

### ISSUE THREAD

**Issue by brummydan** [tlovett1/custom-contact-forms#73]
Hi,

I'm trying to add a form using:

if ( function_exists( 'ccf_output_form' ) ) {
   					 ccf_output_form( FORM_ID );
					}

but I can't, for the life of me, find where the form id is on a form I've created in the recent update..!

**Comment by tlovett1** [comment]
When you go to view a forms submissions, the form ID will be in the URL.

**Comment by brummydan** [comment]
Cheers - presumably the post=36936 part? If so, will it show up in our index php file? I'm adding it with the code above and that ID and it doesn't show…or am I being thick!

**Comment by tlovett1** [comment]
ID is 36936

**Comment by brummydan** [comment]
Cool, so do I replace FORM_ID with the number?

**Comment by tlovett1** [comment]
Correct

**Comment by knowndesign** [comment]
Is there some other way of getting the FORM_ID if there are no submissions?

**Comment by tlovett1** [comment]
If you edit the form, it will be in the URL.

**Comment by knowndesign** [comment]
Ah! I see! Thank you for the help.
