### ISSUE TITLE
Cannot delete submissions

### ISSUE THREAD

**Issue by andrew60103** [tlovett1/custom-contact-forms#75]
The X is there but has no effect...

**Comment by tlovett1** [comment]
Are you using any caching plugins?

**Comment by andrew60103** [comment]
Hi Taylor,
No caching in use. The delete X is clickable but nothing happens. The adjacent 'eye' symbol works ok. I found out when I tried to delete my test submissions. 
The new system is a big improvement over the old one but shame that we lost our archive of submissions. There might have been a few recent enquiries I had not picked up when the update came in.
I also had some problems saving the new form. much like another commenter, I had to have 3 or 4 goes before it finally started saving when I saved after adding each field. Doing the whole lot at once didnt seem to go down too well.
Here is the page with the form, not that I can see how this might help! http://blackheathfencing.org.uk/contact/
Thanks Andrew 07887 821443

**Comment by tlovett1** [comment]
Are there any JavaScript errors when you try to delete?

**Comment by andrew60103** [comment]
hi Taylor, no java script errors. just click and nothing happens. is there a log i could check or a debugger i could run?

I could try plugin elimination if you think it's a conflict. 

Andrew Nisbet
07887 821443
Sent from Yahoo Mail on Android

**Comment by andrew60103** [comment]
| hi Taylor, no java script errors. just click and nothing happens. is there a log i could check or a debugger i could run?

I could try plugin elimination if you think it's a conflict. 
Andrew Nisbet
07887 821443
Sent from Yahoo Mail on Android 
|  From:"Taylor Lovett" <notifications@github.com>
Date:Tue, 3 Mar, 2015 at 16:44
Subject:Re: [custom-contact-forms] Cannot delete submissions (#75)



 Are there any JavaScript errors when you try to delete?—
Reply to this email directly or view it on GitHub.    |

 |

**Comment by tlovett1** [comment]
Can you try the plugin elimination?

**Comment by webstractions** [comment]
In regards to script errors, I do believe you need to define SCRIPT_DEBUG in your configuration file.

`define('SCRIPT_DEBUG', true);`

**Comment by andrew60103** [comment]
Well, strangely enough it has started working! Cant say I have updated any Javascript oriented plugins lately.
As I said, a much easier to configure and better looking form. Just hadnt realised the upgrade had knocked the old form out of action. (You did say MAY need reconfiguring!) Not sure it how long we have not had a contact page!
Do we need to see the slugs appearing on the submitted form, though? And I dont see a strong need for the senders IP address. Most of the time I reply to the contact by forwarding the notification and do not always remember to delete the IP address. If we need it we could look at the submission record?
Cheers Andrew 07887 821443

**Comment by tlovett1** [comment]
Hey Andrew, glad you got it working. I'll take your suggestions into account. For now, the IP will be in the email.

**Comment by webstractions** [comment]
:+1:  on the submitted form slugs.

Would agree with Andrew about leaving the IP address in the form submission. 

I did notice something regarding the web url in the body for emails with repond-to domains that are different in Gmail, but will raise a different issue to that regard.
