### ISSUE TITLE
Submission Table Headings Uses Field-ID's not Field Labels

### ISSUE THREAD

**Issue by webstractions** [tlovett1/custom-contact-forms#76]
Any chance to have the submission table for a form to use the actual field labels, and not the field-id's? The use of field id's makes it look "unfinished" and a little tacky.

Additionally, field id's are shown in parenthesis in the email from the submission. I am at a loss as to why they should have a need to be shown.

**Comment by tlovett1** [comment]
Field labels are too long to show in table headers.

Fields can have the same label. The point of the slug is to help identify.

**Comment by webstractions** [comment]
Regarding fields can have the same label, that is not true. Field IDs should be lower-case usually, and not include spaces. 

There is still the issue of having the Field ID in parenthesis along with the label in the email submission. If I go the route of naming the ID same as label, well it is duplicitous. If I don't rename the Field ID, I still can't see the reason for having to see that all in an email that a client would be using ... It means nothing to them.

**Comment by tlovett1** [comment]
Fields can have the same label.

I will consider removing slug from email. It is the kind of situation where someone gets left out no matter what.

**Comment by webstractions** [comment]
How about a filter?

**Comment by tlovett1** [comment]
I can add that :)

**Comment by webstractions** [comment]
Cool beans! :)

**Comment by tlovett1** [comment]
Added to Github. Will be pushed to .org with the next version.

**Comment by webstractions** [comment]
Awesome. You are the man! Thanks.
