### ISSUE TITLE
Placeholder text for Phone Field is incorrect

### ISSUE THREAD

**Issue by webstractions** [tlovett1/custom-contact-forms#77]
Just an FYI - I was testing phone number field with the default placeholder text and format of `(xxx) xxx-xxxx` and that creates a validation error.

It took me a couple of whacks at it and determined the correct format is `xxx-xxx-xxxx` without the parenthesis.

**Comment by tlovett1** [comment]
This should have been fixed in the newest version. What version are you running?

**Comment by webstractions** [comment]
I am using Version 6.4.10 and I discovered what was going on. There cannot be any spaces in the phone number, otherwise it won't validate. 

Probably allow for spaces in validation? You are allowing for parenthesis and hyphens, suggest you add spaces to the list.

In the meantime, I am going with a placeholder example of `xxx-xxx-xxxx` just to hopefully avoid user confusion.

![Phone Validation Error](http://cfi.webstractions.net/wp/wp-content/uploads/2015/03/ccf-phone-validation-error.jpg)

**Comment by tlovett1** [comment]
This is fixed. Thanks for the report!

**Comment by webstractions** [comment]
You are welcome. And thanks for your work also.

**Comment by tlovett1** [comment]
Please leave a positive plugin review :)

**Comment by webstractions** [comment]
I'll do that! :+1:
