### ISSUE TITLE
Gmail suspects phishing on emails with Sent-from has different domain

### ISSUE THREAD

**Issue by webstractions** [tlovett1/custom-contact-forms#78]
I noticed this quirk when I used the submitters email address field as the sent-from field option for form notifications.

From what I gather, and suspect, is the web url link at the end of the email may be causing this. Or not. Could be any address domain in this field other than the originating domain is just making Gmail wary.

![Gmail phishing warning](http://cfi.webstractions.net/wp/wp-content/uploads/2015/03/ccf-form-submission-email-phishing.jpg)

**Comment by webstractions** [comment]
hmm. This might be a false positive. Since I used my own email as the From and To, it appears that may have triggered the phishing warning. Sheesh. Stupid me. :)

I tried some other fake emails in its place and so far no warnings. Just ignore this altogether.

**Comment by tlovett1** [comment]
Thanks for the report!
