### ISSUE TITLE
Cannot seem to insert form into post

### ISSUE THREAD

**Issue by agodlydeciple** [tlovett1/custom-contact-forms#79]
I built a simple contact form and it saved properly and everything, but when I try to insert it into my post, the 'Insert into Post' link doesn't work and neither does the 'Insert into Post' button.  Thoughts?

**Comment by tlovett1** [comment]
Have you checked for plugin conflicts?

**Comment by agodlydeciple** [comment]
at the time of writing the issue I had not. I will go back and check to see if there were any conflicts.

**Comment by tlovett1** [comment]
Any luck?

**Comment by agodlydeciple** [comment]
unfortunately I haven't had any time. As I am sure there is a plugin conflict somewhere, I won't be able to check in full anytime soon due to a demanding job. I will close the issue so as to not waste your time and will contact you again, if and when I have a chance to look into the issue further. Thank you for your assistance with this matter.
