### ISSUE TITLE
Form Submissions showing in Editor's Insert Link Popup

### ISSUE THREAD

**Issue by webstractions** [tlovett1/custom-contact-forms#80]
When adding a link to some text in the post editor, the popup modal window shows the form submissions. 

![add-link-edit-screen](https://cloud.githubusercontent.com/assets/3614852/6521263/0581af7c-c38a-11e4-908d-1da07d49e1b0.jpg)

I checked your setup for the `ccf_submission` custom post type, and you have the arg for `public` set to false. This should prevent the `wp_link_query()` function in `class-wp-editor.php` file from including them in the results, yet it does.

I'm scratching my head on this. It doesn't look pretty having all of those submissions being listed, especially when there will never be a need to actually link to them in the first place.

**Comment by webstractions** [comment]
As an additional result of the CPT showing in the link popup, it is also showing in Google result pages.

Submissions are showing in a site search with the parameter of `?post_type=ccf_submission&p=149` in the Url.

There needs to be a way to hide from both. Yes?

**Comment by tlovett1** [comment]
I'll make sure this gets fixed.

**Comment by tlovett1** [comment]
@webstractions can you post a link to your site? The link dropdown issue is fixed.

**Comment by webstractions** [comment]
The site is at http://controlfreek.com

As for the links appearing in the Google index, that was probably my fault in letting them know about it. Another plugin (Yoast SEO) for creating sitemaps was responsible and I immediately excluded those (ccf_form and ccf_submission) from being submitted. Other sitemap generators may not be so easy to exclude.

**Comment by tlovett1** [comment]
Yea, unfortunately I can't predict how every sitemap plugin works. I have to keep some of the post types public so sitemap plugins will most likely have to be manually configured to remove form/submission post types.

**Comment by tlovett1** [comment]
This is fixed.
