### ISSUE TITLE
Plugin no longer works on site

### ISSUE THREAD

**Issue by jubrane** [tlovett1/custom-contact-forms#83]
I get the following message when I go to a edit page the form is included on:
Custom Contact Forms is experiencing issues.
There is an issue with synchronizing data. Please try deactivating all other plugins and activating the TwentyFifteen theme. If this fixes the problem, you have a plugin or theme conflict. If it does not, please post in the support forums or Github.

Also, my form no longer shows up in the admin.
And when I try to create a new form, I also get the above error.

I did as suggested and deactivated all plugins except CCF and switch my theme to 2015 but that did not help.

Thanks,
Elias

**Comment by tlovett1** [comment]
Please email tlovett88 [at] gmail
