### ISSUE TITLE
Not Receiving email from form

### ISSUE THREAD

**Issue by gdtg** [tlovett1/custom-contact-forms#86]
I have created a form on http://getdinnertogo.com/careers/ page. Once the form is complete, we are not receiving and email with the form info in it. I have tried the WordPress default email, custom email, etc. 

I have also turned off all my plugins and changed themes as the pop up message requested. Please investigate as soon as possible. It does list the form submission in the form list but we have no idea when one is submitted.

Please let me know when this is resolved.

Kind Regards
dm

**Comment by tlovett1** [comment]
Do WordPress lost password emails send?

**Comment by gdtg** [comment]
There is a bug in your plugin software. I changed forms plugins to another one and it everything works find now.

 

Sorry.

 

Kind Regards

Drexel Mitchell

 

GetDinnerToGo.com

We Make Dinner So You Don’t Have To

Website www.GetDinnerToGo.com <http://www.getdinnertogo.com/> 

Twitter @getdinnertogo
