### ISSUE TITLE
form not working on MAC

### ISSUE THREAD

**Issue by geo789** [tlovett1/custom-contact-forms#87]
tested form on PC, Ipad seem to work.  on Mac it isn't working tried multiple macs.  http://nlhdgroup.com/register/

**Comment by tlovett1** [comment]
I just tested the form in Chrome/Mac. It worked fine although the font color was messed up.

**Comment by geo789** [comment]
Seems to be okay now nothing wrong with this plugin.  Everything was registering properly.  Thank you for your quick response!

**Comment by tlovett1** [comment]
No problem!
