### ISSUE TITLE
Customize Email Submission from simple Custom Contact Form

### ISSUE THREAD

**Issue by staylor505** [tlovett1/custom-contact-forms#88]
I have read all the Issues and still can't get my form customized to display something other than WordPress (form email address) and the issue with the Form Submission to "".
I have a simple contact form with First Name and Last Name fields. Internal Unique Slugs are first-name and last-name respectively. My form does not have a title as the WP theme displays and styles it on every page. I can live with removing the Form Submission to "" entirely as it already displays the site title in the subject. I see you are using the wp_mail function and not sending the name in the header info so that it defaults to WordPress. I would like to replace WordPress with the user's first name and last name. I am attaching an image of a received email with the 2 issues circled in red. Thanks for any DETAILED steps to correct this. BTW I have no idea how to use 'There is a filter to modify the subject. Search for "ccf_email_subject"'. I have been trying everything I know to modify class-ccf-form-handler.php but either get errors or blank screen.
![ccf_example_form_email](https://cloud.githubusercontent.com/assets/1816727/6674617/e4d84850-cbe8-11e4-9121-08be17fcb232.jpg)

**Comment by staylor505** [comment]
Work around; not sure if you have a better suggestion:
(from class-ccf-formhandler.php)
`$headers[] = 'From: ' . sanitize_text_field($_POST['ccf_field_first-name']). " " . sanitize_text_field($_POST['ccf_field_last-name']) . " <". sanitize_email( $submission[$email_field] ).">\n";
								$headers[] = 'Reply-To: ' . sanitize_text_field($_POST['ccf_field_first-name']). " " . sanitize_text_field($_POST['ccf_field_last-name']) . " <". sanitize_email( $submission[$email_field] ).">\n";`

Hard coded the subject line as my form doesn't have a name
`$subject = sprintf( __( '%s: Question/Comment to BEGC Administration', 'custom-contact-forms' )...`

**Comment by tlovett1** [comment]
To change the email subject, add something like this to your functions.php file:

```php
apply_filters( 'ccf_email_subject', function( $subject, $form_id, $email, $form_page ) {
    return 'My new subject line';
} );
```

To change headers:

```php
apply_filters( 'ccf_email_headers', function( $headers, $form_id, $email, $form_page ) {
    return array( 'header1', 'header2' );
} )
````
