### ISSUE TITLE
reCaptcha not showing

### ISSUE THREAD

**Issue by geekysmurf** [tlovett1/custom-contact-forms#89]
The reCaptcha is not showing on the live form.  I believe this is becuase the class name on the div is not the one that Google expects.

Please advise.

**Comment by tlovett1** [comment]
Can you provide a link to the form?

**Comment by geekysmurf** [comment]
http://geekysmurf.com/contact/

**Comment by tlovett1** [comment]
Since you are loading the form via AJAX, you need to call `ccfRecaptchaOnload()` after the AJAX call completes.
