### ISSUE TITLE
Form submission doesn't get redirect nor display any text messag

### ISSUE THREAD

**Issue by lawaraj** [tlovett1/custom-contact-forms#90]
Hey Buddy, 

Loved the plugin and best one till date but have ran into a small issue. When i submit the form, it did send the email but it doesn't display any confirmation message on the screen. Both "Show Text" and "Redirect" doesn't perform any action. After few minutes, i get "Session expired" on recaptcha.

![image](https://cloud.githubusercontent.com/assets/11532607/6702969/e5cf8160-cd87-11e4-8fde-f751db2f3b4e.png)

Any help would be highly appreciated.

**Comment by tlovett1** [comment]
Can you link to the form please?
