### ISSUE TITLE
Adding custom php fields

### ISSUE THREAD

**Issue by duplich** [tlovett1/custom-contact-forms#91]
Hi @tlovett1, thanks so much for the plugin. It looks great, feels great and works as expected-great. 
But I do have a question too: Is it posible to add your own custom php Functions / Fields. More accurately I want to add custom taxonomy as a dropdown or a checkbox. 
The alternative would be to export generated form code and implement it in the page by yourself. Would your consider implementing that feature?

**Comment by tlovett1** [comment]
The plugin is definitely extensible. However, the whole thing relies heavily on Backbone. You would need to cleverly write/extend a number of Backbone views and models. I have it on my list to write a guide for doing this but haven't gotten to it yet. If in the process you need any extra hooks/filters, I am happy to add them for you.

Regarding the second thing, you could hook into form generation on the front end. Again, if there are any missing hooks/filters, I will add them.

**Comment by duplich** [comment]
Thanks for your fast response. 

I decided to go for custom form  from scratch cause I need custom UI based on bootstrap and custom fields in the form. I did use some elements of your HTML form tough :)



—

**Comment by tlovett1** [comment]
Happy to help :)
