### ISSUE TITLE
Forms disappeared off website

### ISSUE THREAD

**Issue by icdesign4u** [tlovett1/custom-contact-forms#93]
I have recently upgraded to the latest version of wordpress and version 6 of the custom contact forms and the forms have dropped off the website pages where they are inserted. I upgraded the database as well.
website is matamatavets.co.nz

**Comment by tlovett1** [comment]
Did you run the upgrade?

**Comment by icdesign4u** [comment]
Yes I did. I changed the form ID which had changed with the upgrade and the forms reappeared, but have lost their styling. I guess I'll need to go into the relevant CSS to redo, unless you have any quicker solution.
Thanks for your reply

Ian

**Comment by tlovett1** [comment]
You will most likely need to do a little restyling. Sorry!
