### ISSUE TITLE
Can't delete submitted forms

### ISSUE THREAD

**Issue by basysaz** [tlovett1/custom-contact-forms#94]
I've set up two forms, each of which has many bogus submissions.  Now that I've added a Captcha to protect from bots I want to clean up the list, but the "X" on the submission record doesn't do anything (and looking at the code in Chrome "Inspect Element" doesn't look like there's any thing there).  The eyeball icon next to the X does drill into the submission as it's supposed to do.

(Sorry if my attempt to paste a screenshot overdid it.)

**Comment by tlovett1** [comment]
Can you email tlovett88 [at] gmail?
