### ISSUE TITLE
ReCaptcha field isn't working on mobile devices

### ISSUE THREAD

**Issue by dploeger** [tlovett1/custom-contact-forms#95]
The embedded ReCaptcha field isn't working on iOS and Android devices. The "I'm not a robot" field simply isn't clickable.

I believe, that this could be related to google. However, perhaps adding another type of Captcha or enabling ReCaptcha advanced options may solve it.

**Comment by tlovett1** [comment]
Can you provide a link to test?

**Comment by dploeger** [comment]
Oh, yes. Sorry. Here's a demo, where the captcha field isn't clickable using iOS 8.2 / Safari:

http://familiensportclub.com/formsdemo

**Comment by tlovett1** [comment]
I'm pretty sure you have some theme CSS that is conflicting with the tap target. Can you try activating a default theme and seeing if it works for you?
