### ISSUE TITLE
Submit button only visible on hover

### ISSUE THREAD

**Issue by macsnorky** [tlovett1/custom-contact-forms#96]
The submit button on my form isn't visible until hovered over with the mouse. It seems to be a theme conflict as it works fine on a generic theme. The theme I'm using is 3Clicks.
www.phuketfoodsafaris.com/enquiry 

Thanks

**Comment by tlovett1** [comment]
Yes, your theme is giving it a white background color. There is nothing the plugin can do. I would suggest you edit your theme's CSS.
