### ISSUE TITLE
Issue with Recaptcha

### ISSUE THREAD

**Issue by skyhawkstudios** [tlovett1/custom-contact-forms#97]
I set up a contact form for a client using Custom Contact Forms, but there is an issue with recaptcha. I inserted recaptcha into the contact form, and entered the site key and secret key. The recaptcha box shows up in the editing page, but when I publish, the box is missing.

In the recaptcha instructions, it says:

"Paste this snippet at the end of the form where you want the reCAPTCHA widget to appear." And then gives a code snippet.

I couldn't find where to enter this code in the Custom Contact Form interface, so possibly this is why it is not showing up. 

The link is here:

http://iofoam.com/contact-io-iodine-soap/

I'm a web designer, not a programmer, so my knowledge of HTML or CSS is pretty rudimentary. 

I appreciate any help you can give. Great plugin overall.

**Comment by tlovett1** [comment]
Did you whitelist your domain in Google?

**Comment by skyhawkstudios** [comment]
Yes, any idea why this is happening?

**Comment by tlovett1** [comment]
Nope, my gut tells me it was configured incorrectly on the Google end. Wish I could be more help :(
