### ISSUE TITLE
Form not submitting or getting emailed 

### ISSUE THREAD

**Issue by sjulau** [tlovett1/custom-contact-forms#99]
When clicking submit, nothing happens on the page, however, I do find the form in my site. 
The form also does not get emailed to me and I am getting forgot password email from Wordpress

**Comment by tlovett1** [comment]
Can you provide a link please?

**Comment by sjulau** [comment]
www.kickassatlifebootcamp.com/feedback
www.lauraslifecoaching.com/feedback

**Comment by tlovett1** [comment]
The first form worked for me. The second one did not.

On the second one it seems there are some JS errors from a cached JS file. Can you try deactivating your caching plugin(s)?

**Comment by sjulau** [comment]
I deactivated the plugin and it's still just spinning

**Comment by sjulau** [comment]
but at the same time I did get the emails from your test

**Comment by sjulau** [comment]
but then when I tried it again .. nothing

**Comment by tlovett1** [comment]
Can you email tlovett88 [at] gmail please

**Comment by sjulau** [comment]
yes thank you!
